### ISSUE TITLE
Directory structure of links

### ISSUE THREAD

**Issue by yuyu2172** [chainer/chainercv#160]
Since there are losses that can be reused between models, it is better to make a directory for losses.
This is from the discussion I had with @mitmul and @rezoo .

I will post my idea of how `links` should be organized.
I put functions (not links) necessary for Faster RCNN under `links.model.faster_rcnn.utils`. I would like a comment on this design.

```
.
└── links
    ├── loss
    │   ├── faster_rcnn_loss.py
    │   ├── semantic_segmentation_loss.py
    │   └── ssd_loss.py
    └── model
        ├── faster_rcnn
        │   ├── faster_rcnn.py
        │   ├── faster_rcnn_vgg.py
        │   └── utils
        │       ├── anchor_target_creator.py
        │       ├── bbox_regression_target.py
        │       ├── generate_anchor.py
        │       ├── proposal_creator.py
        │       └── proposal_target_creator.py
        ├── segnet
        │   └── segnet.py
        └── ssd
            ├── ssd.py
            └── ssd_vgg.py

```

**Comment by yuyu2172** [comment]
Note that I omitted `__init__.py` for brevity.

**Comment by yuyu2172** [comment]
Also note that `links/model` and `links/loss` are good for consistency with `chainer.links`.

**Comment by Hakuyume** [comment]
I think the proposed structure is good. But if we expect losses are reused in other models, it is better to give them names which is not depend on models. For example, `ssd_loss.py` -> `multibox_loss.py` (of course, this name should be discussed).

**Comment by yuyu2172** [comment]
Yeah, `ssd_loss.py` and `faster_rcnn_loss.py` should be discussed.
On `faster_rcnn_loss.py`, it is very difficult to provide it in a general form because it assumes heavily the structure of Faster RCNN.
I think that if losses assume too much about the underlying models, it would be better to put it under `model/MODEL_NAME`.

**Comment by Hakuyume** [comment]
> I think that if losses assume too much about the underlying models, it would be better to put it under model/MODEL_NAME.

I like this solution. Only if we can make a loss general, we should put it into `links/model/loss`.

**Comment by Hakuyume** [comment]
I will implement the loss of SSD in `links/model/ssd/multibox_loss.py` first. If it seems enough general, I will move it into `links/model/loss/<good_name>.py`.

**Comment by Hakuyume** [comment]
I think some utils in Faster-RCNN are useful for SSD. After both models are fixed, I will suggest integration.

**Comment by yuyu2172** [comment]
The issue can be closed.
