### ISSUE TITLE
ImportError: cannot import name voc_detection_label_names

### ISSUE THREAD

**Issue by yonawriter** [chainer/chainercv#241]
What are the causes of the following two errors ?

**Execution result (1):**
`xxxxx@tegra-ubuntu:~/work/chainer-faster-rcnn/chainercv/examples/faster_rcnn/$ python demo.py ***.jpg --gpu 0`

Traceback (most recent call last):
 File "demo.py", line 6, in <module>
  from chainercv.datasets import voc_detection_label_names
ImportError: cannot import name voc_detection_label_names

**Execution result (2):**
`xxxxx@tegra-ubuntu:~/work/chainer-faster-rcnn/chainercv/examples/faster_rcnn/$ python train.py --gpu 0`

Traceback (most recent call last):
 File "train.py", line 18, in <module>
  from chainercv.datasets import voc_detection_label_names
ImportError: cannot import name voc_detection_label_names

**Execution environment:**
 H/W: JetsonTX1
          Memory: 4GB
          HDD: 64GB (Used 27GB=49%)
          CPU: ARMv8 Processor rev 1 (v8l)  x4
                 processer: aarch64
 S/W: OS: Ubuntu 16.04LTS
          chainer: 1.23.0
          ChainerCV: 0.4.5
          OpenCV: 3.1.0
          python: 2.7.12  (64bit)
          LANG: en_US.UTF-8
          Cython: 0.25.2
          matplotlib: 1.5.1
          pillow: 3.1.2
          Numpy: 1.12.1
          CUDA: 8
          cnDNN: 5

 `~/.bashrc`
          export PYTHONPATH=~/work/chainer-faster-rcnn/chainercv/:$PYTHONPATH

**Comment by yonawriter** [comment]
/home/xxxx/.bashrc
 ...
 export PYTHONPATH=/home/xxxx/work/chainer-faster-rcnn/chainercv/:$PYTHONPATH
 ...

**Comment by yuyu2172** [comment]
Have you followed the instruction guide?
http://chainercv.readthedocs.io/en/latest/#install-guide

**Comment by Hakuyume** [comment]
Could you try the following steps?
1. Remove `/home/xxxx/work/chainer-faster-rcnn/chainercv/` from your PYTHONPATH.
    You don't need add ChainerCV directory to PYTHONPATH if ChainerCV is installed successfully.
2. Upgrade your pip environment by `pip install -U chainercv`.
    Chainer 1.23.0 and ChainerCV 0.4.5 are old.

**Comment by yonawriter** [comment]
Thank you for your response.
"pip install -U chainercv" tried but an error occurred. Please tell me if any solution to that.

*****
Try1   Result
*****
xxx@tegra-ubuntu:~$ pip install -U chainercv
Collecting chainercv
...
...
Installing collected packages: chainer, ....
 Found existing installation: chainer 1.23.0
  Uninstalling chainer-1.23.0:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
  ....
  ....
OSError: [Errno 13] Permission denied: '.usr/local/lib/python2.7/dist-packages/chainer-1.23.0-...'

*****
Try2   Result
*****
xxx@tegra-ubuntu:~$ sudo apt-get install libhdf5-dev
xxx@tegra-ubuntu:~$ sudo pip install --upgrade chainer
(chainer 2.0.0 installed successfully)


xxx@tegra-ubuntu:~$ pip install -U chainercv
Collecting chainercv
...
...
Installing collected packages: chainer, ....
 Found existing installation: chainer 2.0.0
  Uninstalling chainer-2.0.0:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
  ....
  ....
OSError: [Errno 13] Permission denied: '.usr/local/lib/python2.7/dist-packages/chainer-2.0.0-py2.7.egg-info/dependency_links.txt'
*****

xxxx@tegra-ubuntu:~/work/chainer-faster-rcnn/chainercv/examples/faster_rcnn/$ python demo.py aaa.jpg --gpu 0

Traceback (most recent call last):
 File "demo.py", line 6, in 
 from chainercv.datasets import voc_detection_label_names
 ImportError: cannot import name voc_detection_label_names
*******

**Comment by Hakuyume** [comment]
How about `pip install --user -U chainercv` ?

**Comment by yonawriter** [comment]
Please ignore the strikethrough line above. A strikethrough line was written without my intention.
xxxx@tegra-ubuntu:$ sudo apt-get install libhdf5-dev
xxxx@tegra-ubuntu:$ sudo pip install --upgrade chainer

**Comment by yonawriter** [comment]
Hakuyume-san, Thank you for your response.
"demo.py" tried but an error occurred. Please tell me if any solution to that.

1. Remove  /home/xxxx/work/chainer-faster-rcnn/chainercv/  from your PYTHONPATH. --->deleted
2. pip install --user -U chainercv  --->  Successfully installed "chainer 1.24.0"
    <Result> 
     chainer: 1.24.0
     ChainerCV: 0.4.9
     pillow: 4.1.1
3. JetsonTX1 restarted.
4. xxxx@tegra-ubuntu:~/work/chainer-faster-rcnn/chainercv/examples/faster_rcnn/$ python demo.py ***.jpg --gpu 0

<Execution result (1)>
Downloading from https://github.com/yuyu2172.share-weights/releases/download/0.0.2/faster_rcnn_vgg16_voc07_2017_05_24.npz...
Trace (most recent call last):
  File "demo.py", line 37, in <module>
    main()
  File ...
  ....
  ....
  IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by yonawriter** [comment]
yuyu2172-san, Thank you for your response.
I have a question about the install-guide. 
 About "https://repo.continuum.io/miniconda/"
  [Install Guide]
    [Anaconda]
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
>Linux-x86_64 ??  

In the following execution environment, which Miniconda2-latest-Linux-?????.sh should I choose from "https://repo.continuum.io/miniconda/"?

<Execution environment>
  H/W: JetsonTX1
         CPU: ARMv8 Processor rev 1 (v8l) x4
         processer: aarch64
  S/W: OS: Ubuntu 16.04LTS(64bit)

**Comment by Hakuyume** [comment]
I guess the https certifications installed in your environment are old or broken.
There are two solutions:
a. Upgrade or fix https certifications.
b. Download the weights file manually.
    You can download the weights file from https://github.com/yuyu2172/share-weights/releases/download/0.0.2/faster_rcnn_vgg16_voc07_2017_05_24.npz
    Please download this file and put it under `~/.chainer/dataset/pfnet/chainercv/models/`.

**Comment by yuyu2172** [comment]
> In the following execution environment, which Miniconda2-latest-Linux-?????.sh should I choose from "https://repo.continuum.io/miniconda/"?

Since you are running a 64 bit machine, https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh will work.
If you want to run on Python 3 environment, please install from a script for Python 3.

**Comment by yonawriter** [comment]
Hakuyume-san, Thank you for your response.
I ran "solution No.2", but also an error occurred. Please tell me if any solution to that.

***********************************************************
<Try-1>
xxxx@tegra-ubuntu:~/work/chainer-faster-rcnn/chainercv/examples/faster_rcnn/$ python demo.py aaa.jpg --gpu 0

<Result-1>
Traceback (most recent call last):
 File "demo.py", line 37, in <module>
   main()
File ....
....
File "/home/ubuntu/.local/lib/python2.7/site-packages/chainer/functions/connection/linear.py", line 45, in forward y += b
File "cupy/core/core.pyx", line 998, in cupy.core.ndarray.__iadd__ (cupy/core/core.cpp:23489)
File ...
...
OSError: Failed to run 'nvcc' command. Check PATH environment variable: [Error 12] Cannot allocate memory

***********************************************************
<Try-2> GPU option none => Executed by CPU
xxxx@tegra-ubuntu:~/work/chainer-faster-rcnn/chainercv/examples/faster_rcnn/$ python demo.py aaa.jpg

<Result-2>
-->No error occurred. Objects were successfully detected ! !
     ( The resulting image was displayed ! ex. persion: 1.00, car: 1.00, dog: 0.97, ... )
***********************************************************

**Comment by Hakuyume** [comment]
> Failed to run 'nvcc' command. Check PATH environment variable

If you want to use GPU acceleration, you need to setup CUDA environment. Please install CUDA tools and make `nvcc` available in PATH.

**Comment by yonawriter** [comment]
Execution result of "train.py"
What are the causes of the following an error ?

xxxx@tegra-ubuntu:~/work/chainer-faster-rcnn/chainercv/examples/faster_rcnn/$ python train.py

>Result
Now loading caffemodel (usually it may take few minutes )
Traceback (most recent call last):
 File "train.py", line 126, in <module>
  main()
 File .......
 File "..../faster_rcnn/faster_rcnn_vgg.py", line 151, in __init__
   self.copy_imagenet_pretrained_vgg16
 File .......
AttibuteError: 'module' object has no attribute 'SetAllowOversizeProtos'

**Comment by yuyu2172** [comment]
You have a problem with protobuf.
I assume that the error occurred at the following line.
https://github.com/chainer/chainer/blob/v1.23.0/chainer/links/caffe/caffe_function.py#L31

Can you update protobuf to the latest version?

**Comment by yuyu2172** [comment]
By the way, it would probably be impossible to train a Faster R-CNN on TX1 for memory issue.

**Comment by yonawriter** [comment]
yuyu2172-san, in this training, how much memory size ?

**Comment by yuyu2172** [comment]
11GB for GPU.

**Comment by yonawriter** [comment]
Hakuyume-san, 
I installed CUDA, cuDNN etc on JetsonTX 1 using JetPack 64 bit by referring to the following site.

Http://takesan.hatenablog.com/entry/2016/06/26/005516

Also, I can check the nvcc information by executing the following command.
$ Nvcc --version
...... NVCC Version xxxxxx
$ Which nvcc
/usr/local/cuda-8.0/bin/nvcc

Furthermore, I wrote to the .bashrc file, export PATH = .......: / usr / local / cuda - 8.0 / bin / nvcc: $ PATH. However, the same error occurs.

What should I do other than these?

**Comment by yonawriter** [comment]
yuyu2172-san,
I trained all the downloaded training data, I understood that it will be 11 GB.
The memory of JetsonTX1 is 4GB.
I think that a normal PC also has less capacity than 11 GB, but can I run train.py even with a normal PC?
If I use my own training data (eg about 5 training data), can I train using JetsonTX 1 with less than 4 GB of memory?

**Comment by yuyu2172** [comment]
How about using AWS?

**Comment by yonawriter** [comment]
yuyu2172-san, I think it's a very good idea.
However, I want to use it inside my company, and the training data is data that I can not bring out outside the company. Therefore, I would like to build a development environment that can be easily trained using JetsonTX 1 which is a machine with GPU in my company.

**Comment by yuyu2172** [comment]
Have you succeeded in running demo.py?

**Comment by yonawriter** [comment]
About the execution result of demo.py, I wrote the details in my comment eleventh from the bottom of isuue # 241.

"demo.py -- gpu 0 caused an error, but running of demo.py (running by CPU) succeeded."

I can use JetsonTX 1 in my company only on weekdays (except Saturday, Sunday and holidays).
Among the solutions proposed to issue # 241, the work I have not yet tried is the following work.

No.1 
 Installation of miniconda. An error occurred and it can not be installed.

No.2 
 Review of setting of CUDA environment (demo.py). I do not know how to rebuild CUDA.

No.3 
Upgrade of protobuf (train.py). We are investigating because we do not know how to upgrade. It will be helpful if you can tell me how to upgrade.

No.4 
After trying No. 3, execute train.py (train.py). Using less than 10 images I created, I confirm that I can do 'transfer learning' in an environment of 4 GB or less.

that's all.

**Comment by yonawriter** [comment]
About the execution result of demo.py, I wrote the details in my comment
eleventh from the bottom of isuue # 241.

"demo.py -- gpu 0 caused an error, but running of demo.py (running by CPU)
succeeded."

I can use JetsonTX 1 in my company only on weekdays (except Saturday,
Sunday and holidays).
Among the solutions proposed to issue # 241, the work I have not yet tried
is the following work.

No.1 Installation of miniconda. An error occurred and it can not be
installed.
No.2 Review of setting of CUDA environment (demo.py). I do not know how to
rebuild CUDA.
No.3 Upgrade of protobuf (train.py). We are investigating because we do not
know how to upgrade. It will be helpful if you can tell me how to upgrade.
No.4 After trying No. 3, execute train.py (train.py). Using less than 10
images I created, I confirm that I can do 'transfer learning' in an
environment of 4 GB or less.

that's all.

P.S. Your question on this (6/3 8:56) does not seem to have been added to
isuue # 241. Is this email private?


2017/06/03 8:56 "Yusuke Niitani" <notifications@github.com>:

**Comment by yonawriter** [comment]
yuyu2172-san,

About No.2
>Can you update protobuf to the latest version?

Although I have not updated protobuf (I do not know how to update), I confirmed that it is Protobuf == 3.3.0 version when running pip freeze. I think this is the latest version.

**Comment by yuyu2172** [comment]
I tried it with `protobuf>=3` with Python 2, and I had error too.
Can you downgrade protobuf version to 2.6?

By the way, it worked with Python 3 and `protobuf>=3`.

**Comment by yuyu2172** [comment]
By the way you can install protobuf with version 2.6 by the following commands.

```
pip uninstall protobuf
pip install protobuf==2.6
```

**Comment by yonawriter** [comment]
yuyu2172-san,
The running result of train.py by after downgrading protobuf is as follows.

**TRY1**
'xxxxxx@tegra-ubuntu:$HOME/work/chainer-faster-rcnn/chainercv$ time python ./examples/faster_rcnn/train.py
Now loading caffemodel (usually it may take few minutes)
Killed

real	0m37.126s
user	0m17.980s
sys	0m6.420s'

**TRY2**
'xxxxxx@tegra-ubuntu:~/work/chainer-faster-rcnn/chainercv$ time python ./examples/faster_rcnn/train.py
Now loading caffemodel (usually it may take few minutes)
Killed

real	0m25.051s
user	0m6.700s
sys	0m6.120s'

**TRY3**
ubuntu@tegra-ubuntu:~/work/chainer-faster-rcnn/chainercv$ shutdown -r now

(continue)

**Comment by yonawriter** [comment]
yuyu2172-san,
\> Have you followed the installation guide?
\> http://chainercv.readthedocs.io/en/latest/#install-guide

**Anaconda**
1. wget https://repo. ...................... miniconda.sh     >> sccessful
2. bash miniconda.sh -b -p $HOME/miniconda         >> ERROR
PREFIX=/home/ubuntu/miniconda
installing: python-2.7.13-0 \...
installing: cffi-1.9.1-py27_0 \...
installing: conda-env-2.6.0-0 \...
\...
installing: pip-9.0.1-py27_1 \...
installing: wheel-0.29.0-py27_0 \...
miniconda.sh: line 297: /home/ubuntu/miniconda/pkgs/python-2.7.13-0/bin/python: cannot execute binary file: Exec format error
ERROR:
cannot execute native linux-64 binary, output from 'uname -a' is:
Linux tegra-ubuntu 3.10.96-tegra #1 SMP PREEMPT Wed Nov 9 19:42:57 PST 2016 aarch64 aarch64 aarch64 GNU/Linux

**Comment by yonawriter** [comment]
Hakuyume-san,

`Failed to run 'nvcc' command. Check PATH environment variable
If you want to use GPU acceleration, you need to setup CUDA environment. Please install CUDA tools and make nvcc available in PATH.`
` No.2
 Review of setting of CUDA environment (demo.py). I do not know how to rebuild CUDA. `

I reconfirmed the CUDA environment. I do not think there is any problem. See below for details.
Please tell me why using `\--gpu 0` will result in an error.

**CUDA environment**
`xxxxx@tegra-ubuntu:/usr/lib/aarch64-linux-gnu$ which nvcc
/usr/local/cuda-8.0/bin/nvcc`

`xxxxx@tegra-ubuntu:/usr/lib/aarch64-linux-gnu$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Fri_Jul_15_14:52:12_CDT_2016
Cuda compilation tools, release 8.0, V8.0.33`

`xxxxx@tegra-ubuntu:/usr/lib/aarch64-linux-gnu$ find ./ -name 'libcudnn.so*'
./libcudnn.so
./libcudnn.so.5
./libcudnn.so.5.1.5`

`xxxxx@tegra-ubuntu:/usr/lib/aarch64-linux-gnu$ cat /usr/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR      5
#define CUDNN_MINOR      1
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)
#include "driver_types.h" `

`xxxxx@tegra-ubuntu:/usr/lib/aarch64-linux-gnu$ cat ~/.bashrc | grep nvcc
 export PATH=/usr/local/cuda-8.0/bin:$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$HOME/miniconda/bin:$PATH:/usr/local/cuda-8.0/bin/nvcc:$PATH`

**Rnnning result**
`
xxxxx@tegra-ubuntu:~/work/chainer-faster-rcnn/chainercv/examples/faster_rcnn$ time python demo.py --gpu 0 a.jpg
Traceback (most recent call last):
  File "demo.py", line 37, in <module>
    main()
  File "demo.py", line 28, in main
    bboxes, labels, scores = model.predict([img])
  File "/home/ubuntu/.local/lib/python2.7/site-packages/chainercv/links/model/faster_rcnn/faster_rcnn.py", line 289, in predict
    img_var, scale=scale, test=True)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/chainercv/links/model/faster_rcnn/faster_rcnn.py", line 158, in __call__
    h, rois, roi_indices, test=test)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/chainercv/links/model/faster_rcnn/faster_rcnn_vgg.py", line 235, in __call__
    fc6 = _relu(self.fc6(pool))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/chainer/links/connection/linear.py", line 93, in __call__
    return linear.linear(x, self.W, self.b)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/chainer/functions/connection/linear.py", line 107, in linear
    return LinearFunction()(x, W, b)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/chainer/function.py", line 199, in __call__
    outputs = self.forward(in_data)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/chainer/functions/connection/linear.py", line 45, in forward
    y += b
  File "cupy/core/core.pyx", line 998, in cupy.core.core.ndarray.__iadd__ (cupy/core/core.cpp:23489)
  File "cupy/core/elementwise.pxi", line 776, in cupy.core.core.ufunc.__call__ (cupy/core/core.cpp:47765)
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret (cupy/util.cpp:1480)
  File "cupy/core/elementwise.pxi", line 584, in cupy.core.core._get_ufunc_kernel (cupy/core/core.cpp:44235)
  File "cupy/core/elementwise.pxi", line 32, in cupy.core.core._get_simple_elementwise_kernel (cupy/core/core.cpp:33912)
  File "cupy/core/carray.pxi", line 86, in cupy.core.core.compile_with_cache (cupy/core/core.cpp:33567)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 156, in compile_with_cache
    cubin = nvcc(source, options, arch)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 78, in nvcc
    _run_nvcc(cmd, root_dir)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 61, in _run_nvcc
    raise OSError(msg)
OSError: Failed to run `nvcc` command. Check PATH environment variable: [Errno 12] Cannot allocate memory

real	0m30.001s
user	0m13.430s
sys	0m6.020s
`

**Comment by yonawriter** [comment]
Please tell me about the following.

**1.**  Please tell me how to run `demo.py` and `train.py` using ***ZF*** and ***VGG_CNN_M_1024*** model in Faster R-CNN.

By quoting the following article, ***ZF*** and ***VGG_CNN_M_1024*** can run with GPU memory size: 3 GB less than 11 GB. I think that these models can be executed using JetsonTX 1 (GPU memory size: 4 GB).
>**Requirements: hardware**
>1. For training smaller networks (***ZF***, ***VGG_CNN_M_1024***) a good GPU (e.g., Titan, K20, K40, ...) with ***at least 3G of memory suffices***
>2. For training Fast R-CNN with VGG16, you'll need a K40 (~11G of memory)
>3. For training the end-to-end version of Faster R-CNN with VGG16, 3G of GPU memory is sufficient (using CUDNN)
>
> https://github.com/rbgirshick/py-faster-rcnn#requirements-hardware

**2.**  How do I run `train.py` using ***SSD*** ?
**3.**  When using ***SSD 300*** or ***SSD 512*** model, how much memory size of GPU is necessary? As you can see below, I have successfully executed with `--gpu` on JetsonTX1, so I think that both are within 4GB.

`.../chainercv/examples/ssd$ python demo.py --gpu 0 --model ssd300 a.jpg`
\-->No error occurred and object detection succeeded !

`.../chainercv/examples/ssd$ python demo.py --gpu 0 --model ssd512 a.jpg`
\-->No error occurred and object detection succeeded !

**Comment by yuyu2172** [comment]
1. You need to implement the models by yourself as they are not supported currently.
2. They are now developed #206.
3. You can check the memory usage on your machine using nvidia-smi

I talked with the questioner face to face and he succeeded in running `demo.py`.
The issue he is having with `train.py` has to do with his hardware setup. This is something we can not do about.
Thanks for asking questions.
If you still have any, please reopen this issue.

**Comment by LaurentBerder** [comment]
In which version of `chainercv` was there a `voc_detection_label_names`?

**Comment by yuyu2172** [comment]
`voc_detection_label_names` has been changed to `voc_bbox_label_names` sinsce v0.7
