### ISSUE TITLE
pickle error.. using chainercv with chainermn 

### ISSUE THREAD

**Issue by MannyKayy** [chainer/chainercv#262]
Hi,

I am trying to use chainercv with chainermn.

I used chainercv with some of my new projects and when i attempt to distribute training using chainermn, I receive the following error from the `scatter_dataset` method. All i am doing is applying a `random_flip` transform to the training data. I get the error for all my projects that use chainercv and have replicated it using the [chainermn mnist example file](https://gist.github.com/MannyKayy/a383b35d70124d7069e78255ed67b452) .

![image](https://user-images.githubusercontent.com/7952854/26975100-46ff5626-4d16-11e7-8ccc-6ab634541a66.png)

I'm not sure as to where to raise this issue so I have raised it in both the chainercv and [chainermn](https://github.com/chainer/chainermn/issues/88) repos.

**Comment by yuyu2172** [comment]
The error occurred because function objects can not be pickled.
We will look into a way to fix this issue. Thank you very much for reporting.

**Comment by yuyu2172** [comment]
Hi. Sorry for the late reply.
Since pickling is the issue, can you put the transform function outside of the main function?

A function can be picklable as long as it is not declared inside another function.
