### ISSUE TITLE
Add classification examples

### ISSUE THREAD

**Issue by yuyu2172** [chainer/chainercv#264]
Although, there are already classification models and examples in main Chainer, it still makes sense to add them to ChainerCV.
Here are reasons why:

1. Chainer's classification models support BGR inputs. It can be reimplemented in ChainerCV while making it consistent with other links here.
2. The example does not reproduce expected performance.
3. Their are no clear explanation on how to prepare imagenet. 
4. The examples in main Chainer can not use all the features that ChainerCV supports such as transforms.

Having said that, there are at minimum three things to do.

- [ ] Add links. Possibly, it can be located at `chainercv.links.model.classifcation`.
- [ ] Prepare `examples/imagenet`, which contains scripts to train and evaluate various classification models.
- [ ] We can use `chainer.datasets.LabeledImageDataset` for imagenet task. However, the current implementation does not force gray scale image to RGB image. This has to be fixed by sending PR to main Chainer. We can also write our own `image_dataset` inside ChainerCV.

**Comment by yuyu2172** [comment]
To make this more concrete, I added a classification link that I would like to add to ChainerCV.
https://github.com/chainer/chainercv/pull/265

**Comment by Hakuyume** [comment]
@yuyu2172 I agree with both 1 and 2. Classification links and datasets in Chainer don't follow the convention of ChainerCV (CHW, RGB). We need our own version (Of course, if we can change the models in Chainer, we don't need ChainerCV version). I think the ChainerCV implementation of fb.resnet.torch is very convenient.

> Add links. Possibly, it can be located at chainercv.links.model.classifcation.

This namespace is not consistent with other existing models. We don't have `chainercv.links.model.detection` or `chainercv.links.model.semantic_segmentation`.

**Comment by yuyu2172** [comment]
> This namespace is not consistent with other existing models. We don't have 
 chainercv.links.model.detection or chainercv.links.model.semantic_segmentation.

OK.
How about `chainercv.links.model.vgg`, `chainercv.links.model.resnet` etc.
We can have different variants of VGGs under `chainercv.links.model.vgg`. For example, VGG16 and VGG19.
This seems better. Thanks for a suggestion.

**Comment by yuyu2172** [comment]
> Of course, if we can change the models in Chainer, we don't need ChainerCV version
The change I would like to introduce (BGR->RGB and a lot of change in API) is too large. I think we can not hope to change the main Chainer code in the way I want.

**Comment by Hakuyume** [comment]
> How about chainercv.links.model.vgg, chainercv.links.model.resnet etc.

Sounds good.

> The change I would like to introduce (BGR->RGB and a lot of change in API) is too large. I think we can not hope to change the main Chainer code in the way I want.

I agree with you. Some of our modifications will not be accepted to Chainer. For example, we need our own VGG-16. I think it is OK.

**Comment by mitmul** [comment]
I agree with both, too.
As for 2., the Keras's `flow_from_directory`-like utility that enables to obtain image classification dataset by just parsing the directory tree, would be nice to have as one of features of it. See here for the details: https://keras.io/preprocessing/image/

**Comment by Hakuyume** [comment]
I think it make ChainerCV more convenient to provide examples that reproduce fb.resnet.torch (https://github.com/facebook/fb.resnet.torch).

**Comment by yuyu2172** [comment]
> As for 2., the Keras's flow_from_directory-like utility that enables to obtain image classification dataset by just parsing the directory tree, would be nice to have as one of features of it. 

I agree with you. This will be really handy, and we should implement it.

**Comment by yuyu2172** [comment]
Done
