### ISSUE TITLE
Segnet train.py no longer reports pixel_accuracy after v2 update

### ISSUE THREAD

**Issue by MannyKayy** [chainer/chainercv#273]
I updated to chainer v2 and the latest chainercv (0.5.1).

If you train the segnet model in the [examples folder](https://github.com/chainer/chainercv/blob/master/examples/segnet/train.py)
 and attempt to log/print the pixel_accuracy, it prints nothing.

![image](https://user-images.githubusercontent.com/7952854/27098410-50ac82fa-506f-11e7-9d5c-a30878f1d5d9.png)

Additionally, the accuracy is no longer logged.

![image](https://user-images.githubusercontent.com/7952854/27097775-53b2de9c-506d-11e7-8318-5ec177327078.png)

For context, this is what the logger looked like before the chainer V2 update.

![image](https://user-images.githubusercontent.com/7952854/27097870-978b60da-506d-11e7-8c33-e47055948bc8.png)

And this is what the log looked like for an epoch where the evaluator was called.

![image](https://user-images.githubusercontent.com/7952854/27097994-eeb0056e-506d-11e7-8549-52f3af88da94.png)

**Comment by Hakuyume** [comment]
@MannyKayy Thank you for using ChainerCV. From my understanding, the values reported in older version were wrong (#215). We are developing an evaluator to report correct accuracy (#238).

**Comment by yuyu2172** [comment]
This issue is fixed.
