### ISSUE TITLE
Lower accuracy for trained models in chainer V2

### ISSUE THREAD

**Issue by MannyKayy** [chainer/chainercv#274]
Not sure if i should post this here or in the main chainer repo.

But I noticed that when i import weights for a model in chainer V2, the performance of the exact same model with the exact same weights is lower than when imported in chainer 1.24.0

DenseNet-FC performance on camvid, evaluated using the [eval_camvid](https://github.com/chainer/chainercv/blob/master/examples/segnet/eval_camvid.py) script.

`Chainer V1.24.0:`

                    Sky : 0.9197
               Building : 0.7507
                   Pole : 0.3796
                   Road : 0.9468
               Pavement : 0.7883
                   Tree : 0.7080
             SignSymbol : 0.5379
                  Fence : 0.2905
                    Car : 0.8405
             Pedestrian : 0.4611
              Bicyclist : 0.3412
==================================
               mean IoU : 0.6331
 Class average accuracy : 0.7767
Global average accuracy : 0.8974

`Chainer V2:`

                    Sky : 0.9168
               Building : 0.7088
                   Pole : 0.3516
                   Road : 0.9430
               Pavement : 0.7343
                   Tree : 0.6241
             SignSymbol : 0.4656
                  Fence : 0.3263
                    Car : 0.8374
             Pedestrian : 0.3786
              Bicyclist : 0.3317
==================================
               mean IoU : 0.6017
 Class average accuracy : 0.7083
Global average accuracy : 0.8819

Is there a way to preserve the performance of models trained in earlier versions of chainer?

**Comment by yuyu2172** [comment]
Do the model output different values in different versions?
Perhaps, train/test setting has changed between the two.

**Comment by yuyu2172** [comment]
Please reopen if more help is needed.
