### ISSUE TITLE
Ask for making model reproducible

### ISSUE THREAD

**Issue by 1991viet** [chainer/chainercv#283]
Hi contributors,
In other frameworks (for example, keras) we could set the random seed to make the model reproducible. Is there any similar way for chainer model, or at least make the output for different times as close as possible ? As I read from here https://docs.chainer.org/en/stable/reference/environment.html , I guess the CHAINER_SEED could be useful here, but I dont know exactly how should I use it. One more way I think about is to use numpy.random.seed at the beginning of the model, but I am not sure whether it is effective or not.
I do need it because I want to apply some improvement for the Faster-rcnn model, and if I cant make the model producible, if I have a better result, I can't know whether it does come from my improvement, or merely come from the randomness
Thank you

**Comment by yuyu2172** [comment]
Hi. I would like to have reproducible experiments, but I haven't fully worked on it.

For Faster R-CNN, there are at least four source of randomness.

+ [Shuffling of dataset](https://github.com/chainer/chainercv/blob/master/examples/faster_rcnn/train.py#L73)
+ [Sampling for ProposalTargetCreator](https://github.com/chainer/chainercv/blob/master/chainercv/links/model/faster_rcnn/utils/proposal_target_creator.py#L114)
+ [Sampling for AnchorTargetCreator](https://github.com/chainer/chainercv/blob/master/chainercv/links/model/faster_rcnn/utils/anchor_target_creator.py#L118)
+ Non-determinstic behavior of Convolution layers (you can turn this off by not using cuDNN).

By setting random.seeds fixed and using non-deterministic convolution layers, it may reproduce results.
