### ISSUE TITLE
Faster-RCNN fails to train in CPU mode

### ISSUE THREAD

**Issue by zori** [chainer/chainercv#290]
`python examples/faster_rcnn/train.py` outputs `nan`s.

> chainercv-faster-rcnn/chainercv/chainercv/links/model/faster_rcnn/faster_rcnn_train_chain.py:154: RuntimeWarning: invalid value encountered in less
>   flag = (abs_diff.data < (1. / sigma2)).astype(np.float32)
> miniconda/envs/ch02/lib/python3.5/site-packages/chainer/functions/activation/relu.py:48: RuntimeWarning: invalid value encountered in greater
>   return utils.force_array(gy[0] * (y > 0)),
> chainercv-faster-rcnn/chainercv/chainercv/links/model/faster_rcnn/utils/proposal_creator.py:126: RuntimeWarning: invalid value encountered in greater_equal
>   keep = np.where((hs >= min_size) & (ws >= min_size))[0]
> iteration   epoch       elapsed_time  lr          main/loss   main/roi_loc_loss  main/roi_cls_loss  main/rpn_loc_loss  main/rpn_cls_loss  validation/main/map.......]  0.20%
> 20          0           306.354       0.001       nan         nan                nan                nan                nan 

As reported offline by @yuyu2172, the CPU implementation of ROIPooling2D returns -np.inf values when ROIs are very small.

The GPU mode is confirmed to train successfully.

**Comment by yuyu2172** [comment]
The bug is fixed here https://github.com/chainer/chainer/pull/2872.
