### ISSUE TITLE
why faster RCNN share convolution feature map with different ROI can improve classify performance than RCNN?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#305]
RCNN feed individual RoI raw pixel area to entire CNN to get feature, But Faster R-CNN in this code share the same feature map produced by VGG among different RoIs, I think this may decrease classify performance because different area(RoI) may have different feature from the begining, share feature map may drop this probability.
Why this method can beyond R-CNN?

**Comment by yuyu2172** [comment]
To my knowledge, what you have mentioned is the distinction between RCNN and Fast R-CNN.
In my understanding, either by feeding a patch to a CNN  or by extracting a patch from the shared features, you get the same kind of values.

**Comment by yuyu2172** [comment]
Since the question is not related to the implementation in ChainerCV, I will close this issue.
