### ISSUE TITLE
ChainerCV release plan

### ISSUE THREAD

**Issue by yuyu2172** [chainer/chainercv#313]
These plans are deprecated. See the actual release plan below.

>After updating to version 0.6 from 0.5, ChainerCV plans to develop under two branches: one for a stable version and the other for a development version. The stable and development versions of ChainerCV support stable and development versions of Chainer respectively. The development version has alpha, beta or RC at the end.
> A major version update for Chainer is released every 12 weeks, and ChainerCV's release cycle is based on that cycle. When Chainer's major version is released, the development branch of ChainerCV becomes the stable branch. The stable branch is maintained until the next major version is released.

>The table below shows the planned release timeline.

>|         | Chainer v2   | Chainer v3  | Chainer v4 | Chainer Dev branch version |
>| ------------- |:-------------:| -----:| -----: | -----: |
>| 0 weeks      | v0.6.0 |   v0.7.0a1 |  |  v3.0.0a1
>| 12 weeks      |   v0.6.x     |    v0.7.0 | v0.8.0a1|  v4.0.0a1 |
>| 24 weeks |    |    v0.7.y     |  v0.8.0|  v5.0.0a1 |

>Note that we have no exact plan on the number of updates to be made between the cycle.

**Comment by sharpstill** [comment]
Do  you have plane to implement more CV algorithm or model? for example,DeepLab for image segmentation

**Comment by yuyu2172** [comment]
We are planning to work on image classification models and their train code.

DeepLab code is requested quite often, but we have no concrete plan to implement it yet.

**Comment by sharpstill** [comment]
I just want to use chainer to implement a network, But last layer is modified from a already written C++ code. Do you have any suggestion?
How to plugin C++ code to chainer as a layer most convenient yet efficient.

**Comment by yuyu2172** [comment]
Are you talking about CRF layer?
You can call C++ functions from Cython code, but it is a lot of hustle to do.

If you are interested in DeepLab network, I would suggest you to start from one without CRF.
The performance seems to be not bad without it.
See table 4 https://arxiv.org/pdf/1606.00915.pdf.

**Comment by yuyu2172** [comment]
# Updated ChainerCV release plan

ChainerCV will continue to develop only on the `master` branch.
Since there are users that use development version and stable version of Chainer, ChainerCV will try to support both versions of Chainer as much as possible.
Our priority is on stable version of Chainer, and we will definitely make sure that ChainerCV works on it.
For the development version, we will support it while possible. This means that CI tests will run with the development version.

Since development and stable versions may have incompatible features, we plan on following the guidelines below.

+ When new class/function is added to Chainer that ChainerCV's functionality needs to use.  --> Copy the class until the development version becomes the stable version.
+ When new feature is added to the existing class/function to Chainer --> Try to support it on both versions using if/else statements. If this is not feasible, only support this feature for the development version of ChainerCV.
+ When recommended style of API usage changes (old style API is deprecated, e.g. deprecation of add_link in v2) --> Use the old style
+ When destructive API change happens  (old API is deleted, e.g. abolish of test kwarg in v2) --> We expect this kind of change extensively affecting ChainerCV will not happen in the near future.
