### ISSUE TITLE
where is `SemanticSegmentationEvaluator`

### ISSUE THREAD

**Issue by crcrpar** [chainer/chainercv#323]
Hi

I tried training SegNet on `chainercv==0.5.1` only to face below

```
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from chainercv.extensions import SemanticSegmentationEvalutor
ImportError: cannot import name SemanticSegmentationEvaluator
```

my env:
- python 2.7.12
- chainer==2.0.0
- chainercv==0.5.1

**Comment by yuyu2172** [comment]
Thanks for reporting.
`SemanticSegmentationEvaluator` has not been added to any release yet (although we will release version with it in a day or so).

There are two ways to run your code.
1. Use example in 0.5.1 branch https://github.com/chainer/chainercv/tree/v0.5.1
2. Or, you can install chainercv at HEAD of this repo.

**Comment by crcrpar** [comment]
Thank you for quick reply.

I got it.
lookin forward to next release
