### ISSUE TITLE
in chainercv/evaluations/eval_detection_voc.py, how to fetch real gt_label?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#324]
I want to modify your code to meet my needs.
In chainercv/evaluations/eval_detection_voc.py, In  def calc_detection_voc_prec_rec
```
pred_bboxes = iter(pred_bboxes)
pred_labels = iter(pred_labels)
pred_scores = iter(pred_scores)
gt_bboxes = iter(gt_bboxes)
gt_labels = iter(gt_labels)
if gt_difficults is None:
    gt_difficults = itertools.repeat(None)
else:
    gt_difficults = iter(gt_difficults)

n_pos = defaultdict(int)
score = defaultdict(list)
match = defaultdict(list)

for pred_bbox, pred_label, pred_score, gt_bbox, gt_label, gt_difficult in \
        six.moves.zip(
            pred_bboxes, pred_labels, pred_scores,
            gt_bboxes, gt_labels, gt_difficults):
...
```
I use pycharm debug to inspect what real object inside gt_labels , It is a iterator or generator, I just try everything but failed to fetch real value inside it?
why is this just a iterator, How can I get real gt_labels out of it?

**Comment by yuyu2172** [comment]
You can do it by at least two ways
1. access values of the iterator in the standard way `gt_labels.next()`.
2. convert the iterator to a list `list(gt_lables)`.

**Comment by sharpstill** [comment]
what is unzip.py in your faster RCNN code file, What is class BufferedIterator used for?

**Comment by yuyu2172** [comment]
I think the doc explains it enough.
https://github.com/chainer/chainercv/blob/master/chainercv/utils/iterator/unzip.py

We wanted to work with an iterator of image instead of a list of images because of memory reason.
These utility tools makes it possible to work very conveniently with iterators.
