### ISSUE TITLE
in detection_voc_evaluator.py, Why observation is empty dict and return?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#329]
in detection_voc_evaluator.py,  I can't google more evaluator example, So I just look at your faster RCNN's detection_voc_evaluator.py example? Do you know how to write a myself evalutor? why below code return an empty dict **observation** ?
```
        report = {'map': result['map']}

        if self.label_names is not None:
            for l, label_name in enumerate(self.label_names):
                try:
                    report['ap/{:s}'.format(label_name)] = result['ap'][l]
                except IndexError:
                    report['ap/{:s}'.format(label_name)] = np.nan

        observation = {}
        with reporter.report_scope(observation):
            reporter.report(report, target)
        return observation
```

**Comment by sharpstill** [comment]
I am a foreigner , I can't read japanese, I googled a lot of chainer example, But most of them is written in japanese, I want to know how to write a **evaluator extension**?

**Comment by yuyu2172** [comment]
Well, I don't know much example other than ones in ChainerCV that modifies Evaluator.

```python
        observation = {}
        with reporter.report_scope(observation):
            reporter.report(report, target)
        return observation
```

This basically does `observation.update(report)`.
By looking at the source code of the original `Evaluator`, you can find that our evaluator simply modified parts of it.

While trying to come up with an answer to your question, I realized that it can be simplified to `return report`.

As a side note, the context `with reporter.report_score(observation)` is useful when `reporter.report` is called inside of a function in the with block.
Here is an example.

```python
import chainer
from chainer import reporter as reporter_module


def f():
    reporter.report({'a': 3})

if __name__ == '__main__':
    observation =  {}

    reporter = reporter_module.Reporter()

    with reporter:
        with reporter_module.report_scope(observation):
            f()

    print(observation)

```

**Comment by sharpstill** [comment]
I just can't find where did it reported ?? in which log file path? I don't see any report F1 score or Accuracy in console print?

**Comment by yuyu2172** [comment]
If you use `LogReport` in your train loop, the values will be printed to a file.
By default, the log file is `result/log`.
(https://github.com/chainer/chainercv/blob/master/examples/faster_rcnn/train.py#L100)

**Comment by sharpstill** [comment]
@yuyu2172 but you also use PrintReport
```
trainer.extend(extensions.PrintReport(
  | ['iteration', 'epoch', 'elapsed_time', 'lr',
  | 'main/loss',
  | 'main/roi_loc_loss',
  | 'main/roi_cls_loss',
  | 'main/rpn_loc_loss',
  | 'main/rpn_cls_loss',
  | 'validation/main/map',
  | ]), trigger=print_interval)
``` 
Does this 2 line conflict with each other, I did not found any report log in my linux filesystem. I am try to find.

**Comment by yuyu2172** [comment]
`mAP` gets recorded on the log file only when it gets evaluated.
You will find it in the log file at iteration 5000.

They don't conflict with each other.

**Comment by yuyu2172** [comment]
If you have more question, please reopen.
