### ISSUE TITLE
chainer faster_RCNN how to extract RoI feature to use in other application

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#333]
Chainer how to extract the RoI or fully connection layer feature in order to use?
is it must after train over? and then load model parameter to extract ? 
How to do that exactly?

**Comment by yuyu2172** [comment]
No you do not ned to train over.
You can extract rois by some subset of methods used inside `FasterRCNN.__call__`.

```python
_, _, H, W = imgs.shape
h = model.extractor(imgs)
_, _, rois, roi_indices, _ = model.rpn(h, (H, W))
```

**Comment by sharpstill** [comment]
@yuyu2172 I think It must load model parameter to extract RoI feature.
My question is load .npz model parameter, does it must simultaneously load optimizer parameter, **Or only load faster_rcnn model parameter is OK?**

**Comment by yuyu2172** [comment]
It works with just model parameters.
Optimizer parameter becomes relevant when you want to retrain the model.
