### ISSUE TITLE
chainer extension argument invoke_before_training=True may not work?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#338]
I use your train.py to train fast_rcnn and modify the evaluate extension and I found the invoke_before_training=True.
I hope to evaluate the model before train and I found it not work as I expected?

**Comment by yuyu2172** [comment]
What do you mean it is not working as expected?
Is it running or is it not reporting values as expected?
I think LogReport needs to be initialized before the Evaluator.

**Comment by sharpstill** [comment]
I mean it will not execute evaluate code before training start.

**Comment by yuyu2172** [comment]
I found that this option is abolished in Chainer v2.
https://docs.chainer.org/en/stable/upgrade.html#extension-invoke-before-training-is-removed

You can evaluate your model outside of the training loop by

```python
evaluator = DetectionVOCEvaluator(
    test_iter, model.faster_rcnn, use_07_metric=True,
    label_names=voc_detection_label_names)
print(evaluator.evaluate())  # the evaluation with a randomly initialized model.


```
