### ISSUE TITLE
chainer.iterators.MultiprocessIterator may cause stop training like zombie process

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#341]
the program when using **chainer.iterators.MultiprocessIterator**  to prefetch batch to train, at first it may speed up to train and I am satisfactory.
Then after several hours training , the chainer.iterators.MultiprocessIterator   may stop training and GPU usage is 0% and CPU usage is 0% as well.
**I am currently using OS centos 7.0 and anaconda 3 with chainer v2**
log:

> | NVIDIA-SMI 375.51                 Driver Version: 375.51                    |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  Tesla K40m          Off  | 0000:01:00.0     Off |                    0 |
> | N/A   36C    P0    63W / 235W |   9887MiB / 11439MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> |   1  Tesla K40m          Off  | 0002:01:00.0     Off |                    0 |
> | N/A   36C    P0    62W / 235W |   8854MiB / 11439MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID  Type  Process name                               Usage      |
> |=============================================================================|
> |    0     34113    C   /usr/local/anaconda3/bin/python3              9883MiB |
> |    1     34113    C   /usr/local/anaconda3/bin/python3              8850MiB |
> +-----------------------------------------------------------------------------+

**Comment by sharpstill** [comment]
When I use ps aux|grep python command and discovery there is defunct python process.
It will may be bug inside it?
`root      34180 39.1  0.0      0     0 ?        Z    12:19  26:39 [python3] <defunct>`

**Comment by yuyu2172** [comment]
Is the bug caused by running examples in ChainerCV?
I am not sure whether the Chainer's iterator has problem or your code has a bug.

**Comment by sharpstill** [comment]
Oh, May be this is the reason, When I use linux to use chainer.iterators.MultiprocessIterator to train.
Subprocess will be create by master process. But I use `nohup` command to boot master train.py process.
When I lost connection to linux server or quit terminal, there is NOHUP signal send to all process running in Linux. May be at this time, although the master process is using `nohup`, but sub-processs to prefetch data batch which created by master process is not using `nohup`.
So when I quit terminal , it will be zombie process.
May be this is reason and I am doing experiment to test my hypothesis.

**Comment by sharpstill** [comment]
no, it still has zombie process problem , the chainer.iterators.MultiprocessIterator  must has bug compatible with centos

**Comment by sharpstill** [comment]
I am 100% sure this is bug inside chainer.iterators.MultiprocessIterator . When I change to chainer.iterators.SerialIterator, everything goes normal

**Comment by yuyu2172** [comment]
Could you make a simple example that reproduces your problem?
