### ISSUE TITLE
how to convert caffemodel to chainer loadable model npz file

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#346]
I notice that you have written a class called SSDCaffeFunction(caffe.CaffeFunction) in the caffe2npz.py, it is specified only used for SSD
for example, I want to convert googLEnet or other complex network caffemodel to chainer loadable npz.
How should I do that?

**Comment by yuyu2172** [comment]
You have to write your own conversion code.
A conversion code for Googlenet is here.
https://github.com/chainer/chainer/blob/master/chainer/links/model/vision/googlenet.py#L376

**Comment by sharpstill** [comment]
@yuyu2172 I still don't know how to get ndarray in your example code:
 https://github.com/chainer/chainer/blob/master/chainer/links/model/vision/googlenet.py#L376
How to load caffemodel?

**Comment by yuyu2172** [comment]
It uses CaffeFunction.
https://github.com/chainer/chainer/blob/master/chainer/links/model/vision/googlenet.py#L176

**Comment by sharpstill** [comment]
@yuyu2172 suppose I want to transfer ResNet 101 to chainer loadable npz file format. But How do I know the key string representation in caffemodel.

**Comment by yuyu2172** [comment]
`dir(src)`
