### ISSUE TITLE
your code substract mean pixel values but is fixed and not compute by actual images?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#352]
your code in
https://github.com/chainer/chainercv/blob/master/chainercv/links/model/faster_rcnn/faster_rcnn_vgg.py#L127
substract mean but this is not compute by actual images,
and further more, mean is not 3-tuple value but is matrix which is H x W x C.
this is example in
https://github.com/chainer/chainer/blob/master/examples/imagenet/compute_mean.py

**Comment by yuyu2172** [comment]
The mean values are copied from the original Faster R-CNN.
I think it is OK because usually the mean values are more or less the same.

The mean image of shape HxWxC can not be used in this case because the shape of the input is undetermined.
