### ISSUE TITLE
Does chainer automatically transfer "def get_example's return data" to GPU inside model?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#354]
I found that in your https://github.com/chainer/chainercv/blob/master/chainercv/datasets/voc/voc_detection_dataset.py#L126 the data is inside np.ndarray which is in CPU.
But your faster_rcnn_train_chain.py def __calll__ : https://github.com/chainer/chainercv/blob/master/chainercv/links/model/faster_rcnn/faster_rcnn_train_chain.py#L63 you assume that your data is already in GPU memory.
Is chainer automatically transfer data to GPU ?

**Comment by yuyu2172** [comment]
Yes.
An updater class transfers data from CPU to GPU.

This method usually does the conversion.
https://github.com/chainer/chainer/blob/master/chainer/training/updater.py#L215
