### ISSUE TITLE
Why argsort 2 times in _hard_negative function in multibox loss function in ssd model?

### ISSUE THREAD

**Issue by yxchng** [chainer/chainercv#357]
```
def _hard_negative(x, positive, k):
    xp = chainer.cuda.get_array_module(x, positive)
    x = chainer.cuda.to_cpu(x)
    positive = chainer.cuda.to_cpu(positive)
    rank = (x * (positive - 1)).argsort(axis=1).argsort(axis=1)
    hard_negative = rank < (positive.sum(axis=1) * k)[:, np.newaxis]
    return xp.array(hard_negative)
```

Can you kindly explain why we need to argsort 2 times here. I cannot figure out. Thanks.

**Comment by Hakuyume** [comment]
I used `argsort` twice in order to get the rank of each element.
The i-th element of `a.argsort().argsort()` indicates the rank of the i-th element of `a`.

Here is a simple example.
```
a: [3, 0, 5, 9, 1]
a.argsort(): [1, 4, 0, 2, 3]
a.argsort().argsort(): [2, 0, 3, 4, 1]
```

**Comment by yxchng** [comment]
One more question, why "hard_negative = rank < (positive.sum(axis=1) * k)[:, np.newaxis]"? I am actually quite puzzled with this mine hard negatives function. Can you explain to me please? Thanks.

**Comment by Hakuyume** [comment]
`rank < N` returns a mask array that indicates each element is in top-N or not.
```
a: [3, 0, 5, 9, 1]
rank: [2, 0, 3, 4, 1]
rank < 3: [True, True, False, False, True]
```
For example, `(rank < 3)[1] (=True)` indicates that `a[1] (=3)` is in top-3 of `a`.

**Comment by yxchng** [comment]
Shouldn't we be taking loss that are the largest? From my understanding, this is taking loss that are smallest?

**Comment by Hakuyume** [comment]
This code takes losses that have large values.
`(x * (positive - 1))` equals to `-x` if `positive` is `0`.
So, `rank` is in descending order.

**Comment by bantmen** [comment]
Sorry for reviving. I tried to explain why the double argsort works here: http://www.berkayantmen.com/rank
