### ISSUE TITLE
how to add penalty/regularization term in chainer to train.

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#360]
suppose I want to use L1 norm( I can't imagine how L1 norm to be calcuate gradient)
Or I want use L2 norm regularization term.
I found in your train.py code:
`optimizer.add_hook(chainer.optimizer.WeightDecay(rate=0.0005))`
does this for doing that L2 norm? how to add another type of penalty term?

**Comment by yuyu2172** [comment]
https://github.com/chainer/chainer/blob/master/chainer/optimizer.py#L606

The hook is called for all parameters after calculating backward pass.

**Comment by yuyu2172** [comment]
How about using lasso hook for L1 regularization.
https://github.com/chainer/chainer/blob/master/chainer/optimizer.py#L637
