### ISSUE TITLE
Why is the implementation of priorbox in SSD in chainer different from that in caffe?

### ISSUE THREAD

**Issue by yxchng** [chainer/chainercv#361]
I can't seem to be able to relate the implementation of priorbox in chainer and the implementation in caffe. The implementation in caffe is here: https://github.com/weiliu89/caffe/blob/ssd/src/caffe/layers/prior_box_layer.cpp.

Can I know why is it different? Is it that you are using different version? As far as I know the caffe version should be the original version?

**Comment by Hakuyume** [comment]
I checked that Chainer implementation returns same prior boxes as Caffe. Why do you think they are different?

**Comment by yxchng** [comment]
I am not saying that the results are different but it seems like the implementation does not follow exactly the caffe implementation? For example, caffe implementation uses xmin, xmax, ymin, ymax but yours seem to use centers, heights and weights. The calculations seems to differ too. Your implementation generates for prior bboxes than the original one. 

I might be wrong though. That's why I am asking.

**Comment by Hakuyume** [comment]
> For example, caffe implementation uses xmin, xmax, ymin, ymax but yours seem to use centers, heights and weights.

Caffe implementation also uses center, height and width in encoding/decoding boxes. The encoded/decoded results should be same.

> The calculations seem to differ too.

Could you tell me the difference?

> Your implementation generates more prior bboxes than the original one.

I checked both implementations generate 8732 prior boxes in SSD300. What does "more prior bboxes" mean?

**Comment by Hakuyume** [comment]
Please note that ChainerCV code does not correspond to the original line-by-line because I optimized the code for Python and numpy.
