### ISSUE TITLE
Why n_class property is needed in PixelwiseSoftmaxClassifier?

### ISSUE THREAD

**Issue by mitmul** [chainer/chainercv#363]
I found `PixelwiseSoftmaxClassifier` assumes that the given model (predictor) should have `n_class` property. But it seems not to be used anywhere in the classifier. Why is this property required? If it's necessary, I think it's better to describe the necessity in the document of this classifier, otherwise, we can't know the model must have `n_class` property before getting an error when trying to use it.

https://github.com/chainer/chainercv/blob/master/chainercv/links/model/pixelwise_softmax_classifier.py#L31

**Comment by yuyu2172** [comment]
Thank you for reporting this.
`n_class` is not necessary in `PixelwiseSoftmaxClassifier`.
It should have been deleted when we modified the implementation to not report IoUs.
