### ISSUE TITLE
Can I know what loss values should SSD has?

### ISSUE THREAD

**Issue by yxchng** [chainer/chainercv#375]
I am in the midst of training SSD and my loss hovers at 20. Can I know what should be a reasonable values? How should the loss curve of SSD look like?

**Comment by Hakuyume** [comment]
Here is a log of SSD300.
![ssd300_voc0712](https://user-images.githubusercontent.com/3014172/29055324-d482ed56-7c36-11e7-9522-24126eab7cfc.png)
