### ISSUE TITLE
What happens if I raise an IndexError in chainer.dataset.DatasetMixin's def get_example function?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#387]
For some reason, I have some bad example data, so in the get_example function, I have to raise IndexError.

But this cause chainer.iterators.MultiprocessIterator, after raise IndexError, the sub-process became zombie process.

How to proceed ignore if raise IndexError anyway?

**Comment by Hakuyume** [comment]
This is not related to ChainerCV.
