### ISSUE TITLE
n_class and pretrained_model are oppsoite order in VGG and other links

### ISSUE THREAD

**Issue by yuyu2172** [chainer/chainercv#406]
`n_class` and `pretrained_model` are taken as arguemnts in the oppsoite order.
https://github.com/chainer/chainercv/blob/master/chainercv/links/model/faster_rcnn/faster_rcnn_vgg.py#L83
https://github.com/chainer/chainercv/blob/master/chainercv/links/model/vgg/vgg16.py#L103

Since `n_class` can be omitted by specifying `pretrained_model`, it might be more convenient to take `pretrained_model` before `n_class`.
This means that the following code is simple.

```python
model = VGG16('imagenet')
```

**Comment by Hakuyume** [comment]
> Since n_class can be omitted by specifying pretrained_model, it might be more convenient to take pretrained_model before n_class.

This depends on which usage is more common. If many users want to train models, `model = VGG16(n_class)` style will be more simple. This is only a suggestion. I'm not sure which case is more common.

Anyway, the order of arguments should be unified.

**Comment by yuyu2172** [comment]
> This depends on which usage is more common. If many users want to train models, model = VGG16(n_class) style will be more simple. This is only a suggestion. I'm not sure which case is more common.

Yeah. You are right.

In terms of choosing the rule, putting `n_class` first seems more consistent with other links.
I think there is an implicit rule that parameters  related to shapes of weights should come first (e.g. `Convolution2D` takes `in_channels, out_channels, ksize` before anything else).

**Comment by Hakuyume** [comment]
If we follow the implicit rule, the order of arguments will be `n_class, pretrained_model`?

**Comment by yuyu2172** [comment]
Yes.
