### ISSUE TITLE
Version dependencies of required libraries for ChainerCV installation

### ISSUE THREAD

**Issue by The-Gupta** [chainer/chainercv#410]
What are the version dependencies of required libraries (Chainer, Pillow, Cython, Matplotlib, OpenCV), with Python 2.7.12 and 3.6.0, for installing all 3 versions of ChainerCV on Anaconda on Windows?

**Comment by yuyu2172** [comment]
Dependency for Chainer is explained in README.
https://github.com/chainer/chainercv#requirements

For the rest of the packages, the versions that get installed in `environment.yml` should work.
https://github.com/chainer/chainercv/blob/master/environment.yml

I am sure that most of the recent versions should work as well.
