### ISSUE TITLE
[Bug?] Comsume unnecessary memory on gpu-0

### ISSUE THREAD

**Issue by naoto0804** [chainer/chainercv#417]
When I run `examples/faster_rcnn/train.py` on gpu with `--gpu gpuno` option,  (note that gpuno is not 0),
The program consumes unnecessary memory (N * 62MiB in many cases) in gpu-0 in addition to correct consumption in gpuno.
Do you know why this happens?

Environment is as follows (maybe this problem is not version-specific):
chainercv=0.6
chainer=3.0.0rc1
cupy==2.0.0rc1

**Comment by Hakuyume** [comment]
I tested `chainer==2.1.0, cupy==0.6.0, and chainercv==0.6.0` but it didn't consumes such unnecessary memory.

**Comment by naoto0804** [comment]
When I clean up the environment and re-install OpenCV that is built with tbb, everything goes well..
I'm sorry to trouble you.
