### ISSUE TITLE
Name of SequentialFeatureExtractor can be improved

### ISSUE THREAD

**Issue by yuyu2172** [chainer/chainercv#425]
Since there is no "extractor" other than "feature extractor", it is safe to name it SequentialExtractor.

**Comment by Hakuyume** [comment]
I agree. `SequentialExtractor` is enough. Perhaps, we can use more general name, such as `SequentialChain` or `SequentialLayers`.

**Comment by yuyu2172** [comment]
`SequentialChain` sounds like "the" only sequential class.
It can be dangerous because there can be other sequential classes (I am not saying that I have a plan to add such class to ChainerCV).

Maybe `SequentialExtractor` is the best.

**Comment by Hakuyume** [comment]
If we have only one sequential class in ChainerCV, it is "the" only sequential class in our namespace. It is safe even if someone define `SequentailChain` in other namespace. I think our model is enough general if we rename `feature` -> `layer`.

**Comment by yuyu2172** [comment]
I am against that idea.
The name of classes in ChainerCV should make as little confusion as possible with names in Chainer.
Since `Sequential` can be added to Chainer in the future, it is better to not make the name too general.

**Comment by Hakuyume** [comment]
If you are afraid of conflict with Chainer, we should ask Chainer-team's opinion. If they add `Sequential` to Chainer, it is better to use it. I don't like two similar classes exist in both Chainer and ChainerCV even if their names are different.

**Comment by Hakuyume** [comment]
If Chainer team is planning to add `SequentialChain` that is completely different from ours, we should use  a name form that users can understand the difference. The name should depend on the difference between Chainer's and ours.

**Comment by yuyu2172** [comment]
There are two options: merge `SequentialFeatureExtractor` with `Sequential` or not.

Merge would require resolving the following differences, which I am not sure if it is possible.

+ `Sequential` has several list operations (e.g. `__add__`, `__mul__`)
+ `SequntialFeatureExtractor` can output intermediate features and combinations of them.

If we are not going to merge them, the names of the two classes can be changed.
Personally, `SequentialFeatureExtractor` or `SequentialExtractor` succinctly describe the difference because the main functionality is "extract feature(s) computed during a single stream of computation".

**Comment by Hakuyume** [comment]
Are you talking about https://github.com/chainer/chainer/pull/2918? If so, I think it is different thing from ours. It seems hard to merge.

I think mitmul-san's model should be named `Sequential(Chain)List` because it is based on `ChainList` and has list operations. And our model can be `SequentialChain` because it have similar APIs to `Chain` and supports name based operations.

**Comment by yuyu2172** [comment]
> And our model can be SequentialChain because it have similar APIs to Chain and supports name based operations.

It is true that our implementation (`SequentialFeatureExtractor`) has operations that make assumptions about the names of the child links.
However, I am not sure if it is necessary to draw parallel between `Sequntial*` and `Chain/Chainlist`. 
I think that they are misleading because the difference between `SequentialChain` and `SequentialList` is not the same as the difference between `Chain` and `ChainList`.
Also, the functionality of `SequentialChain` is not so obvious from the name.

In that sense, naming the class `SequentialExtractor` is better because `Extractor` implies its functionality.

**Comment by Hakuyume** [comment]
> However, I am not sure if it is necessary to draw parallel between Sequntial* and Chain/Chainlist.

It is better (not necessary) to introduce parallel if possible. It makes things clear.

> Also, the functionality of SequentialChain is not so obvious from the name.
>
> In that sense, naming the class SequentialExtractor is better because Extractor implies its functionality.

As you pointed out, `SequentialChain` may not be enough to describe the functionality. It doesn't imply that users can pick values from middle layers. On this point, `Extractor` is better than `Chain`.

Some neural network architectures are separated into (feature) extractor and the rest. This may be the reason why I feel `Extractor` a little bit specific. For example, Faster R-CNN is separated into `extractor`, `rpn`, and `head`. I feel `extractor` of Faster R-CNN and `SequentialExtractor` are different concepts.

**Comment by yuyu2172** [comment]
> I feel extractor of Faster R-CNN and SequentialExtractor are different concepts.

`SequentialExtractor` implies that this should be used for CNN (e.g. VGG).
The name may be not intuitive in other applications, but I can not come up with a situation when the problem arises.

**Comment by Hakuyume** [comment]
> The name may be not intuitive in other applications, but I can not come up with a situation when the problem arises.

For example, an architecture that has a common feature extractor (`Sequential A`) and two branches (`Sequential B/C`). It is a little bit strange to use `Extractor` for `B/C`.
```
input -> Sequential A +-> Sequential B -> output 1
                      +-> Sequential C -> output 2
```

**Comment by Hakuyume** [comment]
`Extractor` sounds the input is a batch of images.

**Comment by yuyu2172** [comment]
I see.
Your example makes sense.
What do you think is the most appropriate name?

**Comment by Hakuyume** [comment]
> What do you think is the most appropriate name?

How about `SequentialLayers` or `SequentialPickableLayers`?
At first, I thought `Chain` is good because it is natural to call `B/C` `Chain`. However, as you pointed out, `Chain` doesn't imply the functionality enough. If you want to emphasize this, `SequentialPickableLayers` is better.

**Comment by yuyu2172** [comment]
How about `SequentialPickable`?

**Comment by Hakuyume** [comment]
Do you think `SequentialPickableLayers` is too long? If so, I prefer `SequentialLayers` to `SequentialPickable`.

**Comment by yuyu2172** [comment]
It is okay, but shorter is better.
How about `PickableSequential`?

I do not think `SequentialLayers` implies the functionality.

**Comment by Hakuyume** [comment]
I think the best name depends on Chainer team's plan.

- If chainer/chainer#2918 will be merged as is
    -  We should emphasize our class is based on Chain (not ChainList).
    - `PickableSequential` is not good because it sounds an inheritance of `Sequential`.
- If chainer will have a sequential Chain class without layer select functionality (assume it's name is `<SequentialChain>`)
    - `Pickable<SequentialChain>` is best.
    - Another solution is sending a PR to Chainer to support layer select functionality.
-  If chainer will have no sequential classes
    - `Pickable` is confusing because there is no un-pickable version.
    - We can use `SequentialChain` or `SequentialLayers` because it is the only sequential class.

 I'm asking Chainer team now.

**Comment by yuyu2172** [comment]
Even if Chainer supports `SequentialChain`, it would take more time.

How about changing the name to `PickableSequentialChain`, and move forward? This name is specific enough to not make confusion in the future.
In my plan, v0.7 can be released once this issue and dataset names are settled.

**Comment by beam2d** [comment]
We have not decided yet if we add `Sequential` to Chainer, but if we use the name `Sequential`, the semantics should be similar to ones in other frameworks like [Keras](https://keras.io/models/sequential/) and [PyTorch](http://pytorch.org/docs/master/nn.html#torch.nn.Sequential). If you want to avoid the naming conflicts with Chainer, you may also want to avoid using the same name with different semantics from other frameworks as well, then it's better to use a name more specific than `Sequential` (or `SequentialLayers` or `SequentialChain`, which sounds almost similar as `Sequential`).

**Comment by Hakuyume** [comment]
Considering conflict with other frameworks, it is better to contain `pickable` because both Keras and PyTorch don't support layer selection. 

> How about changing the name to PickableSequentialChain, and move forward?

Ok, `PickableSequentialChain` is a good solution at this point.

**Comment by yuyu2172** [comment]
> the semantics should be similar to ones in other frameworks like Keras and PyTorch

Thanks for you comment.
Our design is more like a generalization of VGG and ResNet in `chainer.links.model.vision`, which I have never seen in other frameworks.
As you said, making the name more specific seems like a better idea.

> Ok, PickableSequentialChain is a good solution at this point.

OK

**Comment by Hakuyume** [comment]
It is better to replace `feature(s)` in `PickableSequentialChain` with `layer(s)` although I suggested to use `feature(s)`.

**Comment by yuyu2172** [comment]
Why?

**Comment by yuyu2172** [comment]
Oh, you gave a reason before.
https://github.com/chainer/chainercv/issues/425#issuecomment-329939046

Yeah, it is true that some output can not be called `feature` (e.g. probability).

**Comment by yuyu2172** [comment]
How about changing the attributes:

+ `layer_names` --> `pick` (usage: `model.pick = ('l1', 'l2_relu')`)
+ `all_layer_names` --> `layer_names`

**Comment by Hakuyume** [comment]
Perhaps, un-pickable version will use `layer_names` as names of all layers. Renaming `layer_names` -> `picked(_layer_names)` will be safe.

**Comment by Hakuyume** [comment]
Yes, I agree with you. Renaming `layer_names/all_layer_names` -> `pick/layer_names` is ok.
Another solution is using `SelectableSequentialChain` and `selection/layer_names`.

**Comment by yuyu2172** [comment]
I prefer `pick` or `picked_layer_names`.
`picked` sounds like the layers that had been picked.

**Comment by yuyu2172** [comment]
> Yes, I agree with you. Renaming layer_names/all_layer_names -> pick/layer_names is ok.
OK

**Comment by Hakuyume** [comment]
> picked sounds like the layers that had been picked.

I agree.

**Comment by Hakuyume** [comment]
> I prefer pick or picked_layer_names.

`picked_layer_names` also sounds to have been picked. `pick` or `selection` is beter.
