### ISSUE TITLE
run demo on frames or video

### ISSUE THREAD

**Issue by seongkyun** [chainer/chainercv#426]
i want to run exampled ssd codes on frame images.

is there any way for this?

**Comment by yuyu2172** [comment]
Yes you can.
Just modify `demo.py`.

**Comment by seongkyun** [comment]
i did it by modifying `demo.py`

for num in range(0, 8):
    path = '/home/han/Dataset/frame_jpg/road' + str(num) + '/'
    
    for filename in os.listdir(path):
        prevTime = time.time()

        img = mpimg.imread(path + filename)
        rclasses, rscores, rbboxes =  process_image(img)

        curTime = time.time()
        sec = curTime - prevTime

        fps = 1/(sec)

        visualization.bboxes_draw_on_img(img, rclasses, rscores, rbboxes, visualization.colors_plasma)

        out = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        _height, _width, _channels = out.shape
        cv2.putText(out, 'FPS : %.3f' % fps,(_width/10, _height/10),color=(0, 0, 255),fontFace=cv2.FONT_HERSHEY_COMPLEX, fontScale=1, thickness=2)
        cv2.imwrite('/home/han/Dataset/result/SSD300/road' + str(num) + '/' + filename, out)
