### ISSUE TITLE
Ask Depthwise separable convolution

### ISSUE THREAD

**Issue by edmBernard** [chainer/chainercv#430]
Is there a implementation in Chainer of the depthwise separable convolution used in [Mobilenet](https://arxiv.org/pdf/1704.04861.pdf) or [Xception](https://arxiv.org/pdf/1610.02357.pdf) ?

**Comment by yuyu2172** [comment]
Is this what you are looking for?
https://github.com/chainer/chainer/pull/2067

**Comment by edmBernard** [comment]
I don't know how I can miss it.
thanks
