### ISSUE TITLE
unable to import voc_bbox_label_names

### ISSUE THREAD

**Issue by prabhat003** [chainer/chainercv#446]
Hi I tried the steps as given in readme.md while running "**python demo.py sample.jpg**" i run into the following issue

  File "demo.py", line 6, in <module>
    from chainercv.datasets import voc_bbox_label_names
ImportError: cannot import name voc_bbox_label_names

could any one help me out here?? i have installed chainercv (0.4.11) and  chainer (1.24.0)

**Comment by Hakuyume** [comment]
Some modules/functions/classes were renamed. Please try examples in v0.4 branch.

**Comment by LaurentBerder** [comment]
How was `voc_bbox_label_names` renamed specifically?
I am using an older piece of code which refers to it and cannot find the right way to correct that code.
