### ISSUE TITLE
Does test_iter in faster_rcnn don't need prepare(possibly bug)?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#449]
in https://github.com/chainer/chainercv/blob/master/examples/faster_rcnn/train.py#L46 there is `prepare `operation in img, but in https://github.com/chainer/chainercv/blob/master/examples/faster_rcnn/train.py#L100 your code just doesn't use Transform to transform(contains  `prepare `and `mirror `image)
is this code correct?

**Comment by sharpstill** [comment]
because def prepare contains substract mean value from each pixel , this means your test_iter simply doesn't substract mean value?

**Comment by yuyu2172** [comment]
All the necessary preprocessing is carried out inside `FasterRCNN.predict`, which is a function that is called inside `DetectionVOCEvaluator`.
