### ISSUE TITLE
Release Request of 0.7.1

### ISSUE THREAD

**Issue by knorth55** [chainer/chainercv#460]
Can you release `0.7.1` including bug fixes?

**Comment by yuyu2172** [comment]
We update the version usually in every two months.

**Comment by knorth55** [comment]
If you have bug fix, it is a good idea to release new version.

**Comment by knorth55** [comment]
IMO, schedule release is for new features.

**Comment by yuyu2172** [comment]
In short, we do not have a resource to develop with a branch exclusively for bug fix.
We need that branch because the master branch contains both new features and bug fixes.

**Comment by knorth55** [comment]
hmmmm, you are right.
it is difficult.
