### ISSUE TITLE
Consider multiple inputs into model

### ISSUE THREAD

**Issue by MannyKayy** [chainer/chainercv#468]
Currently, the additional tools in chainercv expect that a model takes only one input (an image).
So tools such as `apply_prediction_to_iterator.py` are only designed to handle single input models. In some cases, a vision model will take multiple inputs (e.g. VQA or Bi-Linear models) and it would be nice to natively support that.

**Comment by Hakuyume** [comment]
How about adding a new option, `n_arg`? It indicates the number of additional arguments to passed to `predict`.

...
apply_prediction_to_iterator(predict, iterator)  # predict(imgs) is called for each batch
apply_prediction_to_iterator(predict, iterator, n_arg=2)  # predict(imgs, gt0, gt1) is called for each batch
```

In both cases, it returns `imgs, pred_values, gt_values`.
