### ISSUE TITLE
Does this way of writing chainer v2.1.0 fix some first layer parameter for fine tune correct?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#486]
I am sorry I put the question here rather than stackoverflow because I am too hurry for CVPR 2018, which deadline 11.08 I can't wait.
Does this way of writing chainer fix some first layer parameter for fine tune correct?
I am modifying your chainercv faster-RCNN to my research.
I want to **fix some parameter of first serveral layers of chainer to fine tune an already pretrained model:**
```

def __call__(self, x):

    if self.fix:
        with chainer.no_backprop_mode():
            h = self.bn1(self.conv1(x))
            h = F.max_pooling_2d(F.relu(h), 3, stride=2)
            h = self.res2(h)
    else:
        h = self.bn1(self.conv1(x))
        h = F.max_pooling_2d(F.relu(h), 3, stride=2)
        h = self.res2(h)
    h = self.res3(h)
    h = self.res4(h)
    return h

```
Does this using `chainer.no_backprop_mode` correct? I am using resnet101 to fix until res2 layer.

**Comment by yuyu2172** [comment]
Yes.
You can confirm that the weighs are not updating by printing the value of weights.

Something like `res2.disable_update()` will also cancel updating weights.
