### ISSUE TITLE
AttributeError: 'BlobProto' object has no attribute 'array'

### ISSUE THREAD

**Issue by kkk669** [chainer/chainercv#490]
`blobs[0]` is a instance of `BlobProto` and it doesn’t have `array` field but [`data` field](https://github.com/chainer/chainer/blob/3e832ce5dc3e5d3e968c93748c327687b83ef9f9/chainer/links/caffe/protobuf3/caffe_pb2.py#L865). Therefore, I believe that you should use `blobs[0].data` instead of `blobs[0].array` in the following line.

https://github.com/chainer/chainercv/blob/713c380414e2469392ffe0039e457b3125ff60d7/examples/ssd/caffe2npz.py#L75

**Comment by yuyu2172** [comment]
Hi. The master branch no longer works with Chainer v2.
Please use v3, or use the previous release for v2 (https://github.com/chainer/chainercv/tree/v0.7.0).
