### ISSUE TITLE
Issue with running 'faster_rcnn' example

### ISSUE THREAD

**Issue by HardikChauhanSA** [chainer/chainercv#502]
I am trying to run faster_rcnn example but getting this error,

`sudo python chainercv-master/examples/faster_rcnn/demo.py 004545.jpg `

> Traceback (most recent call last):
>   File "chainercv-master/examples/faster_rcnn/demo.py", line 2, in <module>
>     import matplotlib.pyplot as plot
>   File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 116, in <module>
>     _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
>   File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
>     [backend_name], 0)
>   File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
>     from six.moves import tkinter as Tk
>   File "/usr/local/lib/python2.7/dist-packages/six.py", line 203, in load_module
>     mod = mod._resolve()
>   File "/usr/local/lib/python2.7/dist-packages/six.py", line 115, in _resolve
>     return _import_module(self.mod)
>   File "/usr/local/lib/python2.7/dist-packages/six.py", line 82, in _import_module
>     __import__(name)
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
>     raise ImportError, str(msg) + ', please install the python-tk package'
> ImportError: No module named _tkinter, please install the python-tk package

**Comment by yuyu2172** [comment]
It seems like you have a problem with `matplotlib`.
Can you try to install it by anaconda?
Please see if you can run a simple matplotlib example.
