### ISSUE TITLE
How to specify own dataset, input and output in detection demo

### ISSUE THREAD

**Issue by nightfox8** [chainer/chainercv#510]
Hello,

I have tried to run a detection demo and I received the following output,
Can you explain how can I specify my own dataset, input to this demo?
As far as I can understand it used the PASCALVOC2007 data set right?

> ubuntu:~/chainercv/examples/detection$ python eval_voc07.py 
4952 of 4952 images, 0.47 FPS()
mAP: 0.777661
aeroplane: 0.799549
bicycle: 0.840469
bird: 0.758932
boat: 0.697267
bottle: 0.509548
bus: 0.867976
car: 0.857994
cat: 0.882839
chair: 0.603626
cow: 0.811029
diningtable: 0.765859
dog: 0.863114
horse: 0.875754
motorbike: 0.841525
person: 0.796670
pottedplant: 0.526382
sheep: 0.788620
sofa: 0.801298
train: 0.879323
tvmonitor: 0.785456

Thanks.

**Comment by yuyu2172** [comment]
Change here.
The script is very readable.

https://github.com/chainer/chainercv/blob/master/examples/detection/eval_voc07.py#L54
