### ISSUE TITLE
Suggestion to Implement YOLOv2 within chainercv

### ISSUE THREAD

**Issue by Paul0M** [chainer/chainercv#511]
Since YOLOv2 is so fast, and Chainer is so dynamic. So an official YOLOv2 in Chainercv will be pretty nice!
Even though, there has been one https://github.com/leetenki/YOLOv2, it's time consuming to train on own dataset(Need to know the details of the author's implementation, especially for the dataset preparation).

**Comment by yuyu2172** [comment]
Thank you for your request!

**Comment by LauryMiao** [comment]
New to chainer/chainercv. When I modify leetenki's YOLOv2, I have browsed all the source code of chainer and his repo, but the result doesn't turn out to be good enough. Then I used keras version of YOLOv2, trained on my own data, the result is pretty good. But I prefer chainer/chainercv for it's dynamic and good debuggability. Love chainer!

**Comment by sharpstill** [comment]
YOLO V3 has release, You should re-implement V3 the latest one

**Comment by yuyu2172** [comment]
OK. I made another PR that summarizes detection model.
#603
