### ISSUE TITLE
calc_semantic_segmentation_confusion dynamic matrix

### ISSUE THREAD

**Issue by dokutagero** [chainer/chainercv#517]
In [eval_semantic_segmentation](https://github.com/chainer/chainercv/blob/master/chainercv/evaluations/eval_semantic_segmentation.py) in the function of computing the confusion matrix, since the matrix is defined dynamically based on the value of labels/ground_truth , is it necessary to define a 1D confusion matrix in line 37? Maybe I'm missing something but I think any reference to confusion could be removed and make use only of expanded confusion.

**Comment by yuyu2172** [comment]
Hi. Thanks for asking!
I think we need to initialise the array. 
If we remove line 37, line 52 would raise error.
https://github.com/chainer/chainercv/blob/master/chainercv/evaluations/eval_semantic_segmentation.py#L52

**Comment by dokutagero** [comment]
The thing is that that assignment is assigning to zeros the elements of the matrix, which is done in the previous line, 51.

**Comment by yuyu2172** [comment]
Maybe I am missing something, but I think these lines are still needed.

As you said, in the first loop, the zeros get inserted to zero matrix.
However, you would need these lines when reaching there again. (You insert previously calculated confusion into the expanded confusion).

**Comment by dokutagero** [comment]
Probably it's me missing something... The question was mainly because the confusion matrix is initialized as an empty matrix and ```n_class``` is hardcoded as zero so I was not seeing the point of that initial confusion matrix.

**Comment by dokutagero** [comment]
My bad...It is completely needed. Thank you for the info!
