### ISSUE TITLE
Multiple label per image Semantic Segmentation metric

### ISSUE THREAD

**Issue by dokutagero** [chainer/chainercv#518]
I am working with @mrteera on a project related to semantic segmentation and we are using Chainer. In our case we are dealing with multiple pixel-wise labels per image done by independent people working on the labeling of the dataset. We aim to compute IoU taking as hits the pixels of the prediction that are in the intersection of the multiple labels and not penalizing the ones that are outside the intersection but within the union. This way we have a more meaningful metric taking into account uncertainty areas in datasets where the there is a lot of variance in the labeling process.

Would this metric (or similar) be useful for Chainer? We are willing to make a PR if this is meaningful. Maybe if you consider another interesting metric for this particular problem we can take a look into it and create a PR.

**Comment by yuyu2172** [comment]
Thanks for your interest!
Is the metric common? Do you know any paper that uses it?

**Comment by dokutagero** [comment]
We are trying to find examples of how to deal with multiple labels per image, but at the moment we haven't found for semantic segmentation. For object detection there's confidence level provided by the labelers but for pixel-wise segmentation we are still not sure which is the standard way to proceed.

When we find a santandard methodology I will post it here, or if anyone can provide feedback on this we will take a look at the implementation :)

**Comment by dokutagero** [comment]
Actually it would be like the _void_ area marked in the labels in the [The PASCAL Visual Object Classes Challenge: A Retrospective](http://host.robots.ox.ac.uk/pascal/VOC/pubs/everingham15.pdf) paper, section 2.4.4. We just realized though that it would probably be as easy as just setting this area as a negative number since it gets masked to positive values in the ```calc_semantic_segmentation_confusion``` https://github.com/chainer/chainercv/blob/a7032f1d9ace6428b100bd20b469acf4889dc3c0/chainercv/evaluations/eval_semantic_segmentation.py#L58

In our case, more than a "confidence" border given by the labeler it has to do with uncertainty by different labelers, so that area should not be taken into account in the metric. This is useful when having multiple labels per image and there's disagreement about the area labeled. Considering this can be avoided already in the metric there's no reason to create a new function, maybe it would be more useful a small script to obtain this disagreement area, I don't know if this could be useful maybe for chainercv.

**Comment by dokutagero** [comment]
We are going to try to develop it for a paper publication, we'll share the code in case it could be useful for Chainer :)

Thank you!
