### ISSUE TITLE
How to train object detector on custom dataset?

### ISSUE THREAD

**Issue by panovr** [chainer/chainercv#521]
May you add some docs for training object detector on custom dataset with chainercv?
Thanks!

**Comment by yuyu2172** [comment]
There is a related issue.
Basically, you need to make a dataset with the same interface as the `*BboxDataset` in ChainerCV.
Then, change the training script to use that dataset.

https://github.com/chainer/chainercv/issues/391

**Comment by panovr** [comment]
@yuyu2172 Thanks!
