### ISSUE TITLE
The source package includes Linux binary files

### ISSUE THREAD

**Issue by gwtnb** [chainer/chainercv#536]
[`chainercv-0.8.0.tar.gz`](https://pypi.python.org/packages/6d/c1/ff40e5642f37fe15d1d987d3fa5834ac8f0630b1540ad74d4dac05708273/chainercv-0.8.0.tar.gz#md5=7ca069e95359829f0e1be7ffa72ebd8c) contains two Linux binary files:

```
$ find chainercv-0.8.0 -name '*.so'
chainercv-0.8.0/chainercv/utils/bbox/_nms_gpu_post.cpython-36m-x86_64-linux-gnu.so
chainercv-0.8.0/chainercv/utils/bbox/_nms_gpu_post.so
```

`chainercv-0.8.0.tar.gz` is a source package, which should not contain platform dependent files. When distributing compiled extensions, one has to distribute wheel files.

**Comment by yuyu2172** [comment]
Thank you for letting us know that.
We will definitely fix this problem in the next release.
