### ISSUE TITLE
Training is terminated.

### ISSUE THREAD

**Issue by doiken23** [chainer/chainercv#561]
Hello, thank you for making ChainerCV. It is a very useful framework.

I tried to train SSD network, but training is terminated unexpectedly on the training.
I have no idea about this error. So, please help me.

<pre>
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  merge_sort: failed to synchronize: unspecified launch failure
Aborted (core dumped)
</pre>

**Comment by yuyu2172** [comment]
Hi. `thrust` is probably not recognied by `cupy`.
`merge_sort` is needed for `cupy.sort`.
Can you check if CuPy is installed properly?

**Comment by doiken23** [comment]
@yuyu2172 

Thank you for helping, but I think cupy is correctly installed.

<pre>
In [1]: import cupy

In [2]: cupy.sort
Out[2]: <function cupy.sorting.sort.sort>
</pre>

**Comment by doiken23** [comment]
I find this error emerge only with my own dataset. So, I will check my dataset.

**Comment by yuyu2172** [comment]
Can you actually call `cupy.sort`?

**Comment by doiken23** [comment]
I find the cause is bug in my dataset.
The order of bbox coordinates is incorrect.

I'm sory and thank you for helping.
