### ISSUE TITLE
Unstable test of FCIS

### ISSUE THREAD

**Issue by Hakuyume** [chainer/chainercv#592]
This assertion sometimes fails.
https://github.com/chainer/chainercv/blob/master/tests/experimental_tests/links_tests/model_tests/fcis_tests/utils_tests/test_mask_voting.py#L36-L37

**Comment by knorth55** [comment]
Can you put an error log URL when travis fails?

**Comment by Hakuyume** [comment]
Sorry, I re-run the test carelessly. The log was overwritten.

**Comment by Hakuyume** [comment]
Since I can't provide the log message, I close this issue. I will re-open when it occurs again.

**Comment by Hakuyume** [comment]
It occurs again.
https://travis-ci.org/chainer/chainercv/jobs/377139613

**Comment by knorth55** [comment]
It does not occur with `Python2.7`, sorry.
I will check with `python3.5`

**Comment by yuyu2172** [comment]
Fixed via #606
