### ISSUE TITLE
why set "n_processes=2" in "examples/ssd/train_multi.py" ?

### ISSUE THREAD

**Issue by mingxiaoh** [chainer/chainercv#600]
hello, @Hakuyume 
would you please explain why you fix n_processes to 2 in "examples/ssd/train_multi.py" ? Thanks in advance.

mingxiao@mingxiao:~/Documents/chainercv/examples/ssd$ git show 42a3b8ea0a13f72507e2ee588f679f9e9c2fe7ca
commit 42a3b8ea0a13f72507e2ee588f679f9e9c2fe7ca
Author: Toru Ogawa <Hakuyume@users.noreply.github.com>
Date:   Wed Apr 11 15:05:42 2018 +0900

    tune #processes

diff --git a/examples/ssd/train_multi.py b/examples/ssd/train_multi.py
index 6b01d286..282703f6 100644
--- a/examples/ssd/train_multi.py
+++ b/examples/ssd/train_multi.py
@@ -94 +94 @@ def main():
-        train, args.batchsize // comm.mpi_comm.size, n_processes=1)
+        train, args.batchsize // comm.mpi_comm.size, n_processes=2)
mingxiao@mingxiao:~/Documents/chainercv/examples/ssd$

**Comment by Hakuyume** [comment]
That value achieved the best training speed in my environment. Please change it considering your CPU, GPU(s), and disk.

Note: this value does not affect the stability of training and the performance of trained model.
