### ISSUE TITLE
Suggest to avoid mutable types for default arguments

### ISSUE THREAD

**Issue by t2kasa** [chainer/chainercv#605]
I would like to suggest to avoid mutable types for default arguments.

Some of functions are defined with default arguments by mutable types.
Since default arguments are evaluated when the function definition is executed, it may occur unexpected side effect.

I wrote two examples about above.
(There are not good examples as appropriate usages, sorry.)

```python
class Base(object):
    def __init__(self, params={}):
        self.params = params


class Derived(Base):
    def __init__(self):
        super(Derived, self).__init__()
        self.params["key"] = "value"


# list and dict are mutable.
derived = Derived()
base = Base()
print(base.params)  # {'key': 'value'}
```

```python
from chainercv.links.model.faster_rcnn import FasterRCNNTrainChain
from chainercv.links.model.faster_rcnn import FasterRCNNVGG16

train_chain1 = FasterRCNNTrainChain(FasterRCNNVGG16(n_fg_class=5))
train_chain2 = FasterRCNNTrainChain(FasterRCNNVGG16(n_fg_class=5))

# ProposalTargetCreator is mutable.
print(train_chain1.proposal_target_creator.n_sample)  # 128
print(train_chain2.proposal_target_creator.n_sample)  # 128
train_chain1.proposal_target_creator.n_sample = 256
print(train_chain1.proposal_target_creator.n_sample)  # 256
print(train_chain2.proposal_target_creator.n_sample)  # 256
```

**Comment by Hakuyume** [comment]
Using `None` as a default value is well-known workaround for this problem.

```python
class Base(object):
    def __init__(self, params=None):
        if params is None:
            params = {}
        self.params = params


class Derived(Base):
    def __init__(self):
        super(Derived, self).__init__()
        self.params["key"] = "value"


derived = Derived()
base = Base()
print(base.params)  # {}
```

However, this style has a drawback that users cannot know the actual default value from automatically generated documents.

In the case of `FasterRCNNTrainChain`, I think making `proposal_target_creator` private is a good solution.

**Comment by t2kasa** [comment]
All your comments fully convince me.

Thanks!

**Comment by knorth55** [comment]
Can we close this issue?

**Comment by t2kasa** [comment]
Okay, thanks.

**Comment by knorth55** [comment]
If you think this issue or discussion is still on the way, you can say no.

**Comment by t2kasa** [comment]
The above discussion is understandable for me. 
I think that it is enough as the discussion.

Side effect should be noted generally.
But in this case, using `None` as a default value cannot show expected usage for users.
