### ISSUE TITLE
SSD single node training using "train.py" is much slower than using "train_multi.py"

### ISSUE THREAD

**Issue by mingxiaoh** [chainer/chainercv#613]
hello, we found that using train.py for single node training is much slower than using train_multi.py. 
It seems that it takes a long time in running chainer.iterators.MultiprocessIterator in train.py. Did you see similar issue on your site?

Be notice, even we use train_multi.py, only one node was used.

**Comment by Hakuyume** [comment]
How did you investigate the duration of `chainer.iterators.MultiprocessIterator`? Perhaps, changing `n_processes` has some effect.

**Comment by knorth55** [comment]
can we close this issue?
