### ISSUE TITLE
Faster-RCNN pretrained model does not give the claimed mAP

### ISSUE THREAD

**Issue by apple2373** [chainer/chainercv#624]
```
import chainer
from chainer.iterators import SerialIterator
from chainercv.datasets import VOCBboxDataset
from chainercv.datasets import voc_bbox_label_names
from chainercv.extensions import DetectionVOCEvaluator
from chainercv.links import FasterRCNNVGG16

dataset = VOCBboxDataset(year='2007', split='test')
it = SerialIterator(dataset, batch_size=2, repeat=False, shuffle=False)

model = FasterRCNNVGG16(n_fg_class=len(voc_bbox_label_names),pretrained_model="voc07")

chainer.cuda.get_device_from_id(1).use()
model.to_gpu()

evaluator = DetectionVOCEvaluator(it, model,label_names=voc_bbox_label_names)
# result is a dictionary of evaluation scores. Print it and check it.
result = evaluator()
print(result['main/map'])
```
will give 0.658721191444 but the read me claims it's 70.6 %. (from https://github.com/chainer/chainercv/tree/master/examples/faster_rcnn. )

**Comment by Hakuyume** [comment]
See https://github.com/chainer/chainercv/issues/297 .

**Comment by apple2373** [comment]
Thanks! 
```
import chainer
from chainer.iterators import SerialIterator
from chainercv.datasets import VOCBboxDataset
from chainercv.datasets import voc_bbox_label_names
from chainercv.extensions import DetectionVOCEvaluator
from chainercv.links import FasterRCNNVGG16

dataset = VOCBboxDataset(year='2007', split='test',use_difficult=True,return_difficult=True)
it = SerialIterator(dataset, batch_size=2, repeat=False, shuffle=False)

model = FasterRCNNVGG16(n_fg_class=len(voc_bbox_label_names),pretrained_model="voc07")


chainer.cuda.get_device_from_id(1).use()
model.to_gpu()

model.use_preset('evaluate')

evaluator = DetectionVOCEvaluator(it, model,label_names=voc_bbox_label_names,use_07_metric=True)

result = evaluator()
print(result['main/map'])
```
will give 0.706189614738, which is the same as claimed one. 

I assume model.use_preset('evaluate') is for a general evaluation  so we should apply when evaluating on other datasets but the others (use_difficult, return_difficult, and use_07_metric), are only for PASCAL VOC.

**Comment by Hakuyume** [comment]
> the others (use_difficult, return_difficult, and use_07_metric), are only for PASCAL VOC.

`use_difficult` and `return_difficult` are specific to PASCAL VOC because the annotation of difficulties are not general. On the other hand, `use_07_metric` is a general option. This method can work on any datasets although `use_07_metric=False` is more common today.

**Comment by apple2373** [comment]
Okay I found something in another VOC document. 
```
The computation of the average precision (AP) measure was changed in 2010 to improve precision and ability to measure differences between methods with low AP
1. Compute a version of the measured precision/recall curve with precision monotonically decreasing, by setting the precision for recall r to the max- imum precision obtained for any recall r′ ≥ r.
2. Compute the AP as the area under this curve by numerical integration. No approximation is involved since the curve is piecewise constant.
```

Is this what is calculated when 'use_07_metric=False'? If so, let's not it in the document.

**Comment by Hakuyume** [comment]
>  In my understanding, average precision (AP) is just area under the curve (AUC) of precision-recall curve. How can we have two different metrics?

See https://en.wikipedia.org/wiki/Evaluation_measures_(information_retrieval)#Average_precision.
`use_07_metric=False` is the 2nd equation and `use_07_metric=True` is the 4th equation.

**Comment by apple2373** [comment]
Thanks! I think it's better to link to the wiki and explicitly mention which one is used.
