### ISSUE TITLE
The host shuts down in training

### ISSUE THREAD

**Issue by 1292765944** [chainer/chainercv#628]
I use two gpus for SSD300 training, and find that the host always shuts down after one validation evaluation (e.g. at 10000th iteration) and couldn't switch over training and validation. What may be the problem for this?

**Comment by Hakuyume** [comment]
Please try following settings.
1. use single GPU (`train.py`)
2. multi GPU without saving snapshot

**Comment by 1292765944** [comment]
@Hakuyume using single GPU is ok but is too slow. 
In multi GPU training, saving snapshot do not lead to this problem, and validation evaluation does.

**Comment by Hakuyume** [comment]
How about decreasing `batchsize` and `test-batchsize` in `train_multi.py` ?

**Comment by knorth55** [comment]
can we close this issue?
