### ISSUE TITLE
Download error on OnlineProductsDataset.

### ISSUE THREAD

**Issue by kurita236** [chainer/chainercv#643]
When I call the OnlineProductsDataset constructor, it returns HTTP 400.
When I check online_products_dataset.py, it downloads from ftp://cs.stanford.edu/cs/cvgl/Stanford_Online_Products.zip.
However, in fact, Stanford_Online_Products.zip is located at http://ftp.cs.stanford.edu/cs/cvgl/.

- **Exact command to reproduce**:python -c "import chainercv; chainercv.datasets.online_pr
oducts.online_products_dataset.OnlineProductsDataset ()"

**Comment by yuyu2172** [comment]
In my environment, download works fine with the constructor.
Can you check if you can download from `ftp://cs.stanford.edu/cs/cvgl/Stanford_Online_Products.zip`.

I actually had a very similar problem when I was a student. I changed to another network, and it worked fine.

**Comment by kurita236** [comment]
My network environment requires proxy with authentication and SSL certificate.
I do not have permission to change to other networks.

I got a zip file in another way, and put it in ".Chainer/_dl_cache/2da57d75f448d9ee0ab8a497240166c6".

Thank you.

**Comment by kmaehashi** [comment]
I'd suggest avoid using FTP and use HTTP whenever possible in the framework.
* FTP does not well work with some proxies
* HTTP assets can be cached by proxies, whereas FTP does not
* Some FTP hosts limits number of users that can be logged in (ie. more likely to raise error than HTTP)
