### ISSUE TITLE
Support COCO2017 instead of COCO2014

### ISSUE THREAD

**Issue by yuyu2172** [chainer/chainercv#651]
COCO2014 and COCO2017 contain exactly the same images. I think we should use newer version by default.
I am suspecting that `val` of 2017 is the same as `valminusminival` of 2014, but I am not sure.
If that is the case, I think it is not necessary to support COCO2014 at all.
If they are different, we can additionally support COCO2014 splits.

**Comment by Hakuyume** [comment]
Accoding to https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md#common-settings-and-notes
> All models were tested on the coco_2014_minival dataset, which is exactly equivalent to the recently defined coco_2017_val dataset.

**Comment by Hakuyume** [comment]
We support both 2014 and 2017 in #694
