### ISSUE TITLE
Masking Images. 

### ISSUE THREAD

**Issue by alokwhitewolf** [chainer/chainercv#653]
Need a feature to apply mask on images to hide certain sections of images. This feature is used in networks that infer and build upon attention maps generated. Case in point - https://arxiv.org/pdf/1802.10171.pdf

**Comment by knorth55** [comment]
Hi, @alokwhitewolf .
Sorry for replying you late.
Normal masking can be done with `numpy` and `cupy` array function, but I'm afraid that I got misunderstood your request.
I looked into your repo https://github.com/alokwhitewolf/Guided-Attention-Inference-Network,
but, in terms of masking, which process are you talking about?
Can you tell us lines where you did masking in your repo?

**Comment by alokwhitewolf** [comment]
Thanks for replying. 

I admit I might have created the issue because chainercv didn't have a particular 'masking' utility. I am closing the issue since I feel the feature can be easily replicated normally.
