### ISSUE TITLE
Define Default Box (Anchor Box) Parameters for SSD

### ISSUE THREAD

**Issue by ahkarami** [chainer/chainercv#666]
Suppose one wants to train the SSD Model on a custom data set (_e.g.,_ [raccoon data set](https://github.com/datitran/raccoon_dataset)). To this end, I think it is vitally important to improve the accuracy of the trained model, the parameters of the **default boxes** (also known as **Anchor Boxes**) modify precisely according to the custom data set. As my investigation in the CahinerCV nice implemented codes, in the script [`multibox_coder.py`](https://github.com/chainer/chainercv/blob/master/chainercv/links/model/ssd/multibox_coder.py) the parameters of the _default boxes_ (_i.e.,_ aspect_ratios, steps & sizes) are defined int the `_init_`. In order to better understand how one can modify these parameters, I have the below questions:
1- Would you please explain how the `sizes` parameters are defined? Has this parameter any relationship with the `Sk parameter` (scale of the default boxes for each feature map in the main SSD paper - ECCV 2016, on page 6, equation (4))? In the main paper, the values of this parameter are between 0.2 up to 0.9; however I saw that in the script [`test_ssd.py`](https://github.com/chainer/chainercv/blob/master/tests/links_tests/model_tests/ssd_tests/test_ssd.py) these values are `sizes=(0.1, 0.25, 1, 1.2)` (_i.e.,_ higher than 1!!!). 

2- Would you please explain the format of tuples of the `aspect_ratios` parameter? For example what is this mean `aspect_ratios=((2,), (2, 3), (2,)))`? 

3- For example, I have used the clustering method (_e.g.,_ K-Means) on the bounding boxes of a custom data set with the format of `(x_min, y_min, x_max, y_max)`. After that, I have founded that the centroid of clusters (_e.g.,_ Number Of Clusters = 3) is something like this: `[(117,142), (157,233), (187,341)]` (in the format of (width of the centroid, height of the centroid)). Now, how can I modify the `aspect_ratios` & `sizes` parameters?

I would appreciate the CahinerCV team if answers my above questions.
Thank you very much

**Comment by Hakuyume** [comment]
1. `sizes` is defined here (https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/ssd_pascal.py#L311-L317). Since `min_sizes[k + 1] == max_sizes[k]`, we merged them into one.

    > I saw that in the script test_ssd.py these values are sizes=(0.1, 0.25, 1, 1.2)

    For `test_ssd.py`, we used dummy values. Do not use these values as reference.

2. `aspect_ratios=((2,), (2, 3), (2,)))` means
    For the first scale, the aspect ratios of anchors are `(1, 1), (1/2, 2), (2, 1/2)`.
    For the middle scale, the aspect ratios of anchors are `(1, 1), (1/2, 2), (2, 1/2), (1/3, 3), (3, 1/3)`.
    For the last scale, the aspect ratios of anchors are `(1, 1), (1/2, 2), (2, 1/2)`.

    If you use `aspect_ratios=((2,), (3, 4), (5, 6, 7)))`, it means
    For the first scale, the aspect ratios of anchors are `(1, 1), (1/2, 2), (2, 1/2)`.
    For the middle scale, the aspect ratios of anchors are `(1, 1), (1/3, 3), (3, 1/3), (1/4, 4), (4, 1/4)`.
    For the last scale, the aspect ratios of anchors are `(1, 1), (1/5, 5), (5, 1/5), (1/6, 6), (6, 1/6), (1/7, 7), (7, 1/7)`.

3. Since the design of optimal anchors is still an open question, I can not tell you a concrete way to determine `anchor_ratios` and `sizes`. Note that you can define the aspect ratios of anchor for each scale.

**Comment by ahkarami** [comment]
Dear @Hakuyume,
Many thanks for the complete reply.
