### ISSUE TITLE
Request for implementation of Mask R-CNN and FPN

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#669]
We request for reproducing this amazing work by Kaiming He et al. : Mask R-CNN : https://arxiv.org/abs/1703.06870
It is ICCV best paper and it only add little code on the basis of Faster R-CNN to do the segmentation task.
Also , we request for reproducing the Feature Pyramid Networks(FPN) for hierarchy RoI feature classification(rather than 16x scale smaller feature for RoI classification)
Paper of FPN is here : https://arxiv.org/abs/1612.03144
You can refer to the code here : https://github.com/CharlesShang/FastMaskRCNN

**Comment by knorth55** [comment]
Already requested in #538
