### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by vbsteja** [chainer/chainercv#677]
i am trying to install chainercv on linux mint 19, with following configuration. 

cuda - 9
linux kernel - 4.15.0-24-generic
 nvidia - 390.48

i am getting the following error.

/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h:194:15: fatal error: limits.h: No such file or directory
     #include_next <limits.h>  /* recurse down to the real one */
                   ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1

any help would be appreciated.

**Comment by Hakuyume** [comment]
Please try chainer's examples (e.g. MNIST) first.

**Comment by Hakuyume** [comment]
I have no idea. Chainer and ChainerCV use very similar configuration.

**Comment by vbsteja** [comment]
i am closing it as the issue is happening only inside conda environment. since chainercv does not have any official builds inside conda environment.
