### ISSUE TITLE
How to do data augmented of images offline to increase the size of a limited dataset?

### ISSUE THREAD

**Issue by iphyer** [chainer/chainercv#683]
I know how to use the `TransformDataset` and `Transform` class to do data augmentation and I find that although I can put multiple operations in `Transform` the returned number of images after data augmentation is still the same. 

My Transform class is like this 

```
import numpy as np

import chainer
from chainer.datasets import TransformDataset
from chainer import training
from chainer.training import extensions
from chainer.training.triggers import ManualScheduleTrigger
from chainercv.extensions import DetectionVOCEvaluator
from chainercv.links import FasterRCNNVGG16
from chainercv.links.model.faster_rcnn import FasterRCNNTrainChain
from chainercv import transforms
from utils import MultiDefectDetectionDataset
from utils import rotate_bbox, random_resize, random_distort, random_crop_with_bbox_constraints
import matplotlib.pyplot as plt
plt.switch_backend('agg')

class Transform(object):
    # initial faster_rcnn
    def __init__(self, faster_rcnn):
        self.faster_rcnn = faster_rcnn
    # Initial datasets, H, W stores the hight and width of the image
    def __call__(self, in_data):
        img, bbox, label = in_data
        _, H, W = img.shape

        # random brightness and contrast
        img = random_distort(img)

        # rotate image
        # return a tuple whose elements are rotated image, param.
        # k (int in param)represents the number of times the image is rotated by 90 degrees.
        img, params = transforms.random_rotate(img, return_param=True)
        # restore the new hight and width
        _, t_H, t_W = img.shape
        # rotate bbox based on renewed parameters
        bbox = rotate_bbox(bbox, (H, W), params['k'])

#         # Random expansion:This method randomly place the input image on
#         # a larger canvas. The size of the canvas is (rH,rW), r is a random ratio drawn from [1,max_ratio].
#         # The canvas is filled by a value fill except for the region where the original image is placed.
        if np.random.randint(2):
            fill_value = img.mean(axis=1).mean(axis=1).reshape(-1,1,1)
            img, param = transforms.random_expand(img, max_ratio=2, fill=fill_value, return_param=True)
            bbox = transforms.translate_bbox(bbox, y_offset=param['y_offset'], x_offset=param['x_offset'])

#       # Random crop
#       # crops the image with bounding box constraints
        img, param = random_crop_with_bbox_constraints(img, bbox, min_scale=0.75, max_aspect_ratio=1.25, return_param=True)
#         # this translates bounding boxes to fit within the cropped area of an image, bounding boxes whose centers are outside of the cropped area are removed.
        bbox, param = transforms.crop_bbox(bbox, y_slice=param['y_slice'], x_slice=param['x_slice'],allow_outside_center=False, return_param=True)
#         #assigning new labels to the bounding boxes after cropping
        label = label[param['index']]
#       # if the bounding boxes are all removed,
        if bbox.shape[0] == 0:
            img, bbox, label = in_data
#         # update the height and width of the image
        _, t_H, t_W = img.shape

        img = self.faster_rcnn.prepare(img)
        # prepares the image to match the size of the image to be input into the RCNN
        _, o_H, o_W = img.shape
        # resize the bounding box according to the image resize
        bbox = transforms.resize_bbox(bbox, (t_H, t_W), (o_H, o_W))

        # horizontally & vertical flip
        # simutaneously flip horizontally and vertically of the image
        img, params = transforms.random_flip(
            img, x_random=True, y_random=True, return_param=True)
        # flip the bounding box with respect to the parameter
        bbox = transforms.flip_bbox(
            bbox, (o_H, o_W), x_flip=params['x_flip'], y_flip=params['y_flip'])
        
        scale = o_H / t_H

        return img, bbox, label, scale
```
And the effect is like this:

<img width="871" alt="screen shot 2018-08-31 at 8 17 26 am" src="https://user-images.githubusercontent.com/1913891/44914700-9ebe3d00-acf6-11e8-8269-aee3209db082.png">

And here is the effects,
Is there any methods I can enlarge the size of the dataset, for example, each original image can generate 5 transformed images? And the size of `training_data` is 64 * 5 instead of 64?

**Comment by knorth55** [comment]
I'm not clear what you want to do, but `TransformDataset` is a method for random data augmentation.
If you want to randomly change an input image into 5 transformed images, you just write your own `Transform` class and set iteration as `5 * iteration`.
If you do not want random factor and enlarge your dataset into `5 * len(dataset)`, i think it is better to set different ids for 5 different transformed images in `dataset` class.

**Comment by iphyer** [comment]
@knorth55 Thank you！Got it！ Yeah, I miss that part. 
The image only holds about the same number of images.
Thank you！

**Comment by iphyer** [comment]
Hi @knorth55, I further think about your suggestions and now is what I am thinking. I have noticed that chainerCV is using online augmentation and what I am thinking is offline augmentation like things explained in this blog[Data Augmentation | How to use Deep Learning when you have Limited Data — Part 2](https://medium.com/nanonets/how-to-use-deep-learning-when-you-have-limited-data-part-2-data-augmentation-c26971dc8ced) because I have limited data size so I really want to increase the size of the dataset and I am wondering if there are any tools in ChainerCV can don that.
Thank you again!

**Comment by knorth55** [comment]
I saw some data augmentation in the website, but all the image augmentation can be done in both online and offline.
You are looking for image augmentation tools with more affine transformation.
ChainerCV now supports functions you can find in https://chainercv.readthedocs.io/en/stable/reference/transforms.html.
If you want to do more augmentation quickly, you can use another tools i.e. https://github.com/aleju/imgaug and https://github.com/mdbloice/Augmentor.
this is my experience, but i often use `imgaug`.

**Comment by iphyer** [comment]
@knorth55  Got you!
Really appreciate!

**Comment by knorth55** [comment]
Also, if you really want to do offline data augmentation, you can run data augmentation script, save augmentated data, write something like `AugmentatedDataset` class and load in `train.py`.

**Comment by iphyer** [comment]
Yes, that's really helpful, Thank you!
