### ISSUE TITLE
Improve random_rotate

### ISSUE THREAD

**Issue by nattochaduke** [chainer/chainercv#684]
For now, chainercv.transforms.random_rotate rotates image by right angle (one of 0, 90, 180, 270 degrees).
However I believe that it is convenient that the degree of rotation is sampled from more fine distribution {i | -180 <= i <= 180} and the range of distribution can be specified, like [pytorch's random_rotate](https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.RandomRotation).
So I propose to add arguments that enables this feature to random_rotate or to add another function to chainercv.transforms.

**Comment by yuyu2172** [comment]
Thanks for your suggestion.
I see both the current implementation and what you proposed convenient, so I should probably have two functions for them.
Thinking about it, I should have probably named the function as `random_rot90`.

**Comment by knorth55** [comment]
this is implemented in #690
