### ISSUE TITLE
Cannot replicate the results in eval_imagenet.py

### ISSUE THREAD

**Issue by maxc01** [chainer/chainercv#715]
I am running eval_imagenet.py, but I cannot replicate the results listed in there. The reference implementation in ChainerCV is:

Model | Top 1 | Reference Top 1
-- | -- | --
VGG16 | 29.0 % | 28.5 % [1]
ResNet50 | 24.8 % | 24.7 % [2]
ResNet101 | 23.6 % | 23.6 % [2]
ResNet152 | 23.2 % | 23.0 % [2]

My running results in the following:

model | top1
-- | --
vgg16 | 0.3149999976
resnet50 | 0.2689999938
resnet101 | 0.2546200156
resnet152 | 0.2479799986

Does anyone have such issues?

**Comment by knorth55** [comment]
Can you give us how to test it like `python eval_imagenet.py --gpu...`?
and also did you follow the dataset instruction as https://github.com/chainer/chainercv/tree/master/examples/classification#how-to-prepare-imagenet-dataset?

**Comment by maxc01** [comment]
Hi, @knorth55, I follow exactly the steps in the README. I run the script like this:
`python eval_imagenet.py /usr/data/val --model vgg16 --gpu 1`

**Comment by maxc01** [comment]
I am closing this issue, because I found the embarrassing reason, my validation data is modified due to some unknown reasons.
