### ISSUE TITLE
A question about mAP implementation in Chainercv

### ISSUE THREAD

**Issue by 1991viet** [chainer/chainercv#719]
Dear contributors.

I found out your great mAP calculation at https://github.com/chainer/chainercv/tree/master/chainercv/evaluations

I tried to use your eval_detection_coco.py to calculate mAP for my pytorch object detection. I prepare the 5 inputs pred_bboxes, pred_labels, pred_scores, gt_bboxes, gt_labels in the same type and structure as described on your script. But when I use your script, it showed me wierd result, as in the screenshot I attach below. I think I did something wrong with one or several input out of 5 inputs. But I am quite sure that I follow strictly your instruction. I also attach my code as a zip file. Could you please take a look at the example.py file, to see if I do anything wrong.

It would be also great if you could give me a real examples of the 5 inputs, then it would be easier for me to understand and avoid mistakes.

The inputs I prepare for your eval script are real output from my Yolo implementation at https://github.com/1991viet/Yolo-pytorch

Thank you for your time. I am looking forward to your reply
Best regards,

Here are my script as well as screenshots
![error](https://user-images.githubusercontent.com/15526232/47613731-b9155c80-da94-11e8-95c1-c9e27b65c21f.png)
![instruction](https://user-images.githubusercontent.com/15526232/47613732-b9155c80-da94-11e8-874e-ec1596d7de15.png)
Link to my script:
https://drive.google.com/open?id=1cpQIWdYiu9tRr9aHYEb4RE7E3FolaHs_

**Comment by yuyu2172** [comment]
> It would be also great if you could give me a real examples of the 5 inputs, then it would be easier for me to understand and avoid mistakes.

Sample inputs and outputs can be downloaded from here
https://github.com/chainer/chainercv/blob/master/tests/evaluations_tests/test_eval_detection_coco.py#L96
https://github.com/chainer/chainercv/blob/master/tests/evaluations_tests/test_eval_detection_coco.py#L97

The tests are passing, so the function seems to function properly.
