### ISSUE TITLE
Support multi gpu and multi batch training for Faster R-CNN  

### ISSUE THREAD

**Issue by apple2373** [chainer/chainercv#735]
Hi, 

I'd like to request to support multi gpu and multi batch training for faster R-CNN. I think these issues are not recognized by the developers because I couldn't find the issue for them, so I am creating the issue. 

(Well, sorry if you are already working on them. I tried to search from the past issues, but I am not so confident, because GitHub search function is not so good.... I referenced the most relevant issue that I was able to find. ) 

1) Support multi batch training
It seems to support only batch size = 1. I found a similar issue (#589) but it's just closed saying that it only support batch size of 1, which is not good! Please support it!  

2) Support multi GPU training 
Not only batch it should support multi GPU training. I found a same issue for YOLO (#627) but couldn't find Faster R-CNN one, so I am requesting here. 

Lastly, this is just FYI, but  I am requesting these functions because they are already supported in popular pytorch implementations.  
https://github.com/jwyang/faster-rcnn.pytorch
https://github.com/facebookresearch/maskrcnn-benchmark

Thanks!

**Comment by fiarabbit** [comment]
https://github.com/chainer/chainercv/issues/735

**Comment by knorth55** [comment]
Faster-RCNN with FPN is supported for multi batch GPU.
https://github.com/chainer/chainercv/blob/master/examples/fpn/train_multi.py
For normal Faster-RCNN, we are planning to rewrite it and support multi GPU training.

**Comment by apple2373** [comment]
Thanks for the multi gpu script, but I can't install chainermn so I couldn't use it. Can you also show the script without chainermn?
