### ISSUE TITLE
Fix a link to pretrained model.

### ISSUE THREAD

**Issue by nattochaduke** [chainer/chainercv#750]
In the implementation of resnet, I found a wrong link to a pretrained model.
The following link must be to resnet-50 pretrained model.
https://github.com/chainer/chainercv/blob/6a0ccda66125985f8a2453995c73fe31e1cccf31/chainercv/links/model/resnet/resnet.py#L112
I believe 'resnet50_imagenet_trained_2018_11_26.npz' should be the correct link, but I haven't checked yet.

**Comment by knorth55** [comment]
Thank you for reporting the issue. I made PR for this #751.
