### ISSUE TITLE
EOF error while running calc_weight.py of SegNet

### ISSUE THREAD

**Issue by sandy9999** [chainer/chainercv#756]
![image](https://user-images.githubusercontent.com/17477947/50586727-da356780-0ea0-11e9-8219-05b45856cd82.png)

This is what I am getting when I run python calc_weight.py, an EOF error, what could be the reason? I have installed the modules and dependencies as mentioned in the README. As a result, class_weight.npy is not getting created and I am not able to train.

**Comment by yuyu2172** [comment]
The latest release is not compatible with the master branch.
If you are using the module downloaded by pip, please use the scripts released in the latest release.
https://github.com/chainer/chainercv/releases/tag/v0.11.0

**Comment by knorth55** [comment]
Can i close this ?

**Comment by knorth55** [comment]
temporarily closed.
If you still have same issue, please reopen.
