### ISSUE TITLE
Documentation source links

### ISSUE THREAD

**Issue by 23pointsNorth** [chainer/chainercv#766]
Currently, when clicking on the `[source]` link under the definition of any method/class, the user is linked to a readthedocs webpage like [this](https://chainercv.readthedocs.io/en/stable/_modules/chainercv/visualizations/vis_bbox.html#vis_bbox). 

Whereas, in the `chainer` documentation it links straight to the function definition on github (i.e. from [here](https://chainer.readthedocs.io/en/stable/reference/generated/chainer.functions.add.html) to [here](https://github.com/chainer/chainer/blob/v5.2.0/chainer/functions/math/basic_math.py#L218) ).

Is there a plan to standartize where the source code is shown?

**Comment by knorth55** [comment]
Which one do you prefer?
You mean you prefer to add a direct link to Github?

**Comment by 23pointsNorth** [comment]
I personally prefer the GitHub link, as it allows me to navigate the rest of the source code quickly. But I think it should be a community decision which way to go.

**Comment by knorth55** [comment]
#768 merged
