### ISSUE TITLE
How can I output the same format log by the trainer's reporter function in eval_semantic_segmentation.py?

### ISSUE THREAD

**Issue by Keiku** [chainer/chainercv#794]
Can I output the log using the function of report in `chainercv/examples/semantic_segmentation/eval_semantic_segmentation.py` ? Is it possible to use the reporter function without relying on the trainer? I would like to get the same result as when train/eval is done with `chainercv/examples/segnet/train.py` with learning rate = 0, iter = 1, and the last trained model. The reason why I want to do this is because I am refactoring code in my work project and I want to eliminate duplication of code. Thank you.

**Comment by knorth55** [comment]
You can run the reporter function without trainer.
But what you want to do is probably this PR in chainer: https://github.com/chainer/chainer/pull/3511

**Comment by Keiku** [comment]
Thank you for the information. I will check the link. 🙇‍♂️
