### ISSUE TITLE
ValueError : import to chainercv using python3.6 or python3.7.

### ISSUE THREAD

**Issue by kurita236** [chainer/chainercv#843]
# System information
- Python: Python 3.6.7 |Anaconda, Inc.| (default, Dec 10 2018, 20:35:02) [MSC v.1915 64 bit (AMD64)] on win32
          or Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)] :: Anaconda custom (64-bit) on win32
- ChainerCV: 0.12.0

- Platform: Windows-10-10.0.17134-SP0
- Chainer: 5.3.0
- NumPy: 1.15.4
- CuPy:
-   CuPy Version          : 5.3.0
-   CUDA Root             : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
-   CUDA Build Version    : 10010
-   CUDA Driver Version   : 10010
-   CUDA Runtime Version  : 10010
-   cuDNN Build Version   : 7500
-   cuDNN Version         : 7500
-   NCCL Build Version    : None
-   NCCL Runtime Version  : None
- iDeep: Not Available

### Describe the problem

When I run as follows using python3.6 or python3.7, An error occurred.
There is no error using python3.5.

> import chainer
> import chainercv

Traceback (most recent call last):
  File "xxxx.py", line 2, in <module>
    import chainercv
  File "xxxx\chainer\lib\site-packages\chainercv\__init__.py", line 4, in <module>
    from chainercv import datasets  # NOQA
  File "xxxx\chainer\lib\site-packages\chainercv\datasets\__init__.py", line 1, in <module>
    from chainercv.datasets.ade20k.ade20k_semantic_segmentation_dataset import ADE20KSemanticSegmentationDataset  # NOQA
  File "xxxx\chainer\lib\site-packages\chainercv\datasets\ade20k\ade20k_semantic_segmentation_dataset.py", line 7, in <module>
    from chainercv.datasets.ade20k.ade20k_utils import get_ade20k
  File "xxxx\chainer\lib\site-packages\chainercv\datasets\ade20k\ade20k_utils.py", line 8, in <module>
    from chainercv import utils
  File "xxxx\chainer\lib\site-packages\chainercv\utils\__init__.py", line 2, in <module>
    from chainercv.utils.bbox.non_maximum_suppression import non_maximum_suppression  # NOQA
  File "xxxx\chainer\lib\site-packages\chainercv\utils\bbox\non_maximum_suppression.py", line 6, in <module>
    from chainercv.utils.bbox._nms_gpu_post import _nms_gpu_post
  File "__init__.pxd", line 872, in init chainercv.utils.bbox._nms_gpu_post
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

**Comment by knorth55** [comment]
can you reinstall chainercv again?

```bash
pip uninstall chainercv
pip install cython
pip install chainercv --no-cache-dir -vvv
```

**Comment by kurita236** [comment]
When I reinstalled from scratch as follows, I was able to import the chainercv.

> conda create -n chainer37 python=3.7 anaconda conda pip git -y
> call activate chainer37

> pip install "git+https: //github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=Python API"
> pip install --upgrade chainer == 5.3.0
> pip install --upgrade cupy == 5.3.0 --no-cache-dir -vvvv
> pip install --upgrade chainercv == 0.12.0 --no-cache-dir -vvvv

**Comment by knorth55** [comment]
can you try `pip install -U numpy`

**Comment by kurita236** [comment]
When I tried agein now, numpy==1.16.2 was installed.

> conda create -n chainer37 python=3.7 anaconda conda pip git -y
> call activate chainer37

> pip install "git+https: //github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=Python API"
> pip install --upgrade chainer == 5.3.0
> pip install --upgrade cupy == 5.3.0 --no-cache-dir -vvvv
> pip install --upgrade chainercv == 0.12.0

> python -c "import chainer; chainer.print_runtime_info()"
Platform: Windows-10-10.0.17134-SP0
Chainer: 5.3.0
NumPy: 1.16.2
CuPy:
  CuPy Version          : 5.3.0
  CUDA Root             : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
  CUDA Build Version    : 10010
  CUDA Driver Version   : 10010
  CUDA Runtime Version  : 10010
  cuDNN Build Version   : 7500
  cuDNN Version         : 7500
  NCCL Build Version    : None
  NCCL Runtime Version  : None
iDeep: Not Available



Even if I import chainercv, There was no errors.

> python -c "import chainer; import chainercv"
