### ISSUE TITLE
Add a img.resize function in utils

### ISSUE THREAD

**Issue by changbaishan** [chainer/chainercv#899]
Sometimes user run into memory error. This problem could be avoided with resizing input image.  A img.resize function in utils package can help users accomplish this. Thanks very much.

**Comment by Hakuyume** [comment]
We already have `transforms.resize`.
https://chainercv.readthedocs.io/en/stable/reference/transforms.html#resize

**Comment by changbaishan** [comment]
Indeed. Thank you very much!
