### ISSUE TITLE
Problem about eval_detection

### ISSUE THREAD

**Issue by kumasento** [chainer/chainercv#913]
Hi there,

Not sure whether this is the place to post such a question, but I'm wondering how to load a trained FPN model (by scripts under `examples/fpn`) to the `eval_detection.py` script for the purpose of evaluation? 

Thanks in advance for any clarification.

**Comment by Hakuyume** [comment]
Please use `--pretrained-model` option.
https://github.com/chainer/chainercv/blob/master/examples/detection/eval_detection.py#L96

**Comment by kumasento** [comment]
Ah thanks! It should work. I misunderstood the code. 😓
