### ISSUE TITLE
Accuracy problems of FCIS example

### ISSUE THREAD

**Issue by otsukaoly** [chainer/chainercv#915]
I'm executing FCIS sample into particle images.
(See #912.)

There are additional problems in accuracy.

1. If there are many particles in the image, number of detected particles is lesser than number of true particles obviously.
Any hyperparameter may be related, but I don't know which hyperparameter is related.

2. If use_preset method of FCIS class is called using not 'visualize' but 'evaluate', the number of detected particles is increased.
(It seems that the method changes self.score_thresh variable from 0.7 to 1e-3.)
However, additional detected particles are represented using the same pattern.
It may be bug.

I appreciate any comments.
If there is suitable site to ask accuracy of FCIS, advise it.

**Comment by knorth55** [comment]
> If there are many particles in the image, number of detected particles is lesser than number of true particles obviously.
Any hyperparameter may be related, but I don't know which hyperparameter is related.

Probably, IoU threshold is related.

>If use_preset method of FCIS class is called using not 'visualize' but 'evaluate', the number of detected particles is increased.
(It seems that the method changes self.score_thresh variable from 0.7 to 1e-3.)
However, additional detected particles are represented using the same pattern.
It may be bug.

What do you mean by same pattern?
can you upload visualized image of your result?

**Comment by otsukaoly** [comment]
> Probably, IoU threshold is related.

Could you explain in detail which parameter you mean in the source code?

> What do you mean by same pattern?
> can you upload visualized image of your result?

I can only upload true images and predicted images.

Case 1.
There are not many particles in the image.
![not_many_particles](https://user-images.githubusercontent.com/44423835/61777287-a10e1600-ae37-11e9-81d4-dd9ee4db2ac3.PNG)

Case 2-A.
In case of use_preset('visualize').
![result_visualize](https://user-images.githubusercontent.com/44423835/61777289-a10e1600-ae37-11e9-848a-f187c266087e.PNG)

Case 2-B.
In case of use_preset('evaluate').
Additional detected particles are represented using the same pattern.
![result_evaluate](https://user-images.githubusercontent.com/44423835/61777288-a10e1600-ae37-11e9-83ee-4e9144e2dfdc.PNG)

**Comment by otsukaoly** [comment]
I uploaded true images and predicted images.
If possible, I need any advice.

**Comment by knorth55** [comment]
I can say nothing about your case because there is no input image.
It seems that training is not done properly, so it is better to check your training log.

**Comment by otsukaoly** [comment]
sorry for my late reply.
I adjusted some of parameters below and resolved 2 problems finally.
Thank you.

```
FCISResNet101
	RegionProposalNetwork
		ratios and anchor_scales
	ProposalCreator
		nms_thresh, n_train_pre_nms, n_train_post_nms, n_test_pre_nms, n_test_post_nms and min_size
	FCISResNet101Head
		n_class, roi_size, group_size, loc_normalize_mean, loc_normalize_std and iter2
	nms_thresh, score_thresh, mask_merge_thresh, binary_thresh, limit and min_drop_size

FCISTrainChain
	rpn_sigma and roi_sigma
	AnchorTargetCreator
		n_sample, pos_iou_thresh, neg_iou_thresh and pos_ratio
	ProposalTargetCreator
		n_sample, pos_ratio, pos_iou_thresh, neg_iou_thresh_hi, neg_iou_thresh_lo and binary_thresh
```
