### ISSUE TITLE
Change Request in chainercv/examples/fpn/train_multi.py

### ISSUE THREAD

**Issue by yechanp** [chainer/chainercv#941]
Hello, 

line 61 in TrainChain Class in chainercv/examples/fpn/train_multi.py ,

I think 
x = np.zeros(
            (len(imgs), 3, pad_size[0], pad_size[1]), dtype=np.float32)
should be changed to 
x = self.xp.zeros(
            (len(imgs), 3, pad_size[0], pad_size[1]), dtype=np.float32) because when model is gpu-mode,  the model use cupy instead of using numpy. 
Am I right?

**Comment by Hakuyume** [comment]
Current code is correct.
In FPN example, all arguments of `TrainChain.forward` is CPU array.
They are sent to GPU in https://github.com/chainer/chainercv/blob/master/examples/fpn/train_multi.py#L66-L69.
